// ==================== SENTENCE DATABASE ====================
const SENTENCES = [
  // ===== INTERROGATIVE - ELEMENTARY =====
  {id:1,text:"What is your name?",type:"interrogative",sub:"general",level:"elementary",cn:"你叫什么名字？"},
  {id:2,text:"How are you today?",type:"interrogative",sub:"general",level:"elementary",cn:"你今天好吗？"},
  {id:3,text:"Where do you live?",type:"interrogative",sub:"special",level:"elementary",cn:"你住在哪里？"},
  {id:4,text:"Do you like coffee?",type:"interrogative",sub:"general",level:"elementary",cn:"你喜欢咖啡吗？"},
  {id:5,text:"What time is it?",type:"interrogative",sub:"special",level:"elementary",cn:"现在几点了？"},
  {id:6,text:"Can you help me?",type:"interrogative",sub:"general",level:"elementary",cn:"你能帮我吗？"},
  {id:7,text:"Is this your book?",type:"interrogative",sub:"general",level:"elementary",cn:"这是你的书吗？"},
  {id:8,text:"Where is the bathroom?",type:"interrogative",sub:"special",level:"elementary",cn:"洗手间在哪里？"},
  {id:9,text:"How much does it cost?",type:"interrogative",sub:"special",level:"elementary",cn:"这个多少钱？"},
  {id:10,text:"Do you have any brothers or sisters?",type:"interrogative",sub:"general",level:"elementary",cn:"你有兄弟姐妹吗？"},
  {id:11,text:"What color do you like?",type:"interrogative",sub:"special",level:"elementary",cn:"你喜欢什么颜色？"},
  {id:12,text:"Are you hungry?",type:"interrogative",sub:"general",level:"elementary",cn:"你饿了吗？"},
  {id:13,text:"When is your birthday?",type:"interrogative",sub:"special",level:"elementary",cn:"你的生日是什么时候？"},
  {id:14,text:"Do you speak English?",type:"interrogative",sub:"general",level:"elementary",cn:"你会说英语吗？"},
  {id:15,text:"Who is your teacher?",type:"interrogative",sub:"special",level:"elementary",cn:"你的老师是谁？"},
  {id:16,text:"Can I have some water?",type:"interrogative",sub:"general",level:"elementary",cn:"我能喝点水吗？"},
  {id:17,text:"What is your favorite food?",type:"interrogative",sub:"special",level:"elementary",cn:"你最喜欢的食物是什么？"},
  {id:18,text:"Is it raining outside?",type:"interrogative",sub:"general",level:"elementary",cn:"外面在下雨吗？"},
  {id:19,text:"How old are you?",type:"interrogative",sub:"special",level:"elementary",cn:"你多大了？"},
  {id:20,text:"Would you like some tea?",type:"interrogative",sub:"general",level:"elementary",cn:"你想喝茶吗？"},
  {id:21,text:"Where are you from?",type:"interrogative",sub:"special",level:"elementary",cn:"你来自哪里？"},
  {id:22,text:"Is this seat taken?",type:"interrogative",sub:"general",level:"elementary",cn:"这个座位有人吗？"},
  {id:23,text:"What day is today?",type:"interrogative",sub:"special",level:"elementary",cn:"今天星期几？"},
  {id:24,text:"Do you want to play?",type:"interrogative",sub:"general",level:"elementary",cn:"你想玩吗？"},
  {id:25,text:"How do you say this in English?",type:"interrogative",sub:"special",level:"elementary",cn:"这个用英语怎么说？"},

  // ===== INTERROGATIVE - INTERMEDIATE =====
  {id:26,text:"Have you ever been to Japan?",type:"interrogative",sub:"general",level:"intermediate",cn:"你去过日本吗？"},
  {id:27,text:"What would you do if you won the lottery?",type:"interrogative",sub:"special",level:"intermediate",cn:"如果你中了彩票你会做什么？"},
  {id:28,text:"Could you tell me where the nearest station is?",type:"interrogative",sub:"general",level:"intermediate",cn:"你能告诉我最近的车站在哪吗？"},
  {id:29,text:"How long have you been studying English?",type:"interrogative",sub:"special",level:"intermediate",cn:"你学英语学了多久了？"},
  {id:30,text:"Would you mind opening the window?",type:"interrogative",sub:"general",level:"intermediate",cn:"你介意开窗吗？"},
  {id:31,text:"Why did you decide to change your career?",type:"interrogative",sub:"special",level:"intermediate",cn:"你为什么决定换职业？"},
  {id:32,text:"Have you finished reading that book yet?",type:"interrogative",sub:"general",level:"intermediate",cn:"你读完那本书了吗？"},
  {id:33,text:"What kind of music do you usually listen to?",type:"interrogative",sub:"special",level:"intermediate",cn:"你通常听什么类型的音乐？"},
  {id:34,text:"Isn't it a beautiful day for a walk?",type:"interrogative",sub:"tag",level:"intermediate",cn:"今天天气很适合散步，不是吗？"},
  {id:35,text:"Do you prefer working from home or the office?",type:"interrogative",sub:"choice",level:"intermediate",cn:"你喜欢在家还是在办公室工作？"},
  {id:36,text:"What are your plans for the weekend?",type:"interrogative",sub:"special",level:"intermediate",cn:"你周末有什么计划？"},
  {id:37,text:"Should we take the bus or walk there?",type:"interrogative",sub:"choice",level:"intermediate",cn:"我们应该坐公交还是步行去？"},
  {id:38,text:"How often do you exercise?",type:"interrogative",sub:"special",level:"intermediate",cn:"你多久锻炼一次？"},
  {id:39,text:"You have been to London before, haven't you?",type:"interrogative",sub:"tag",level:"intermediate",cn:"你以前去过伦敦，对吧？"},
  {id:40,text:"What inspired you to start learning a new language?",type:"interrogative",sub:"special",level:"intermediate",cn:"是什么激励你开始学一门新语言的？"},
  {id:41,text:"Could you recommend a good restaurant nearby?",type:"interrogative",sub:"general",level:"intermediate",cn:"你能推荐附近一家好餐厅吗？"},
  {id:42,text:"Do you think technology makes our lives easier?",type:"interrogative",sub:"general",level:"intermediate",cn:"你认为技术让我们的生活更容易了吗？"},
  {id:43,text:"Where did you grow up?",type:"interrogative",sub:"special",level:"intermediate",cn:"你在哪里长大的？"},
  {id:44,text:"Have you considered applying for that position?",type:"interrogative",sub:"general",level:"intermediate",cn:"你考虑过申请那个职位吗？"},
  {id:45,text:"What makes you happy?",type:"interrogative",sub:"special",level:"intermediate",cn:"什么让你开心？"},
  {id:46,text:"Would you rather travel by train or by plane?",type:"interrogative",sub:"choice",level:"intermediate",cn:"你更愿意坐火车还是飞机旅行？"},
  {id:47,text:"She passed the exam, didn't she?",type:"interrogative",sub:"tag",level:"intermediate",cn:"她通过考试了，不是吗？"},
  {id:48,text:"How do you usually spend your holidays?",type:"interrogative",sub:"special",level:"intermediate",cn:"你通常怎么度过假期？"},
  {id:49,text:"Can you explain this concept to me?",type:"interrogative",sub:"general",level:"intermediate",cn:"你能给我解释一下这个概念吗？"},
  {id:50,text:"What was the most memorable trip you have ever taken?",type:"interrogative",sub:"special",level:"intermediate",cn:"你最难忘的旅行是哪次？"},

  // ===== INTERROGATIVE - ADVANCED =====
  {id:51,text:"To what extent do you think artificial intelligence will reshape the global economy?",type:"interrogative",sub:"special",level:"advanced",cn:"你认为人工智能将在多大程度上重塑全球经济？"},
  {id:52,text:"Wouldn't it be more prudent to diversify the investment portfolio before the fiscal quarter ends?",type:"interrogative",sub:"tag",level:"advanced",cn:"在财季结束前分散投资组合不是更明智吗？"},
  {id:53,text:"How might sustainable urban planning mitigate the effects of climate change?",type:"interrogative",sub:"special",level:"advanced",cn:"可持续城市规划如何能减轻气候变化的影响？"},
  {id:54,text:"Should governments prioritize economic growth over environmental conservation?",type:"interrogative",sub:"choice",level:"advanced",cn:"政府是否应该将经济增长置于环境保护之上？"},
  {id:55,text:"What philosophical implications arise from advances in genetic engineering?",type:"interrogative",sub:"special",level:"advanced",cn:"基因工程的进步会带来哪些哲学层面的影响？"},
  {id:56,text:"Could you elaborate on how quantum computing differs from classical computation?",type:"interrogative",sub:"general",level:"advanced",cn:"你能详细说明量子计算与经典计算有何不同吗？"},
  {id:57,text:"Is it not the case that prolonged social isolation leads to cognitive deterioration?",type:"interrogative",sub:"tag",level:"advanced",cn:"长期社交隔离会导致认知退化，不是吗？"},
  {id:58,text:"To what degree has globalization exacerbated socioeconomic inequality?",type:"interrogative",sub:"special",level:"advanced",cn:"全球化在多大程度上加剧了社会经济不平等？"},
  {id:59,text:"How can educational institutions foster critical thinking in an era of misinformation?",type:"interrogative",sub:"special",level:"advanced",cn:"教育机构如何在错误信息时代培养批判性思维？"},
  {id:60,text:"Would it be feasible to implement universal basic income on a national scale?",type:"interrogative",sub:"general",level:"advanced",cn:"在全国范围内实施全民基本收入是否可行？"},
  {id:61,text:"What role does unconscious bias play in perpetuating systemic discrimination?",type:"interrogative",sub:"special",level:"advanced",cn:"无意识偏见在延续系统性歧视中扮演什么角色？"},
  {id:62,text:"Haven't recent neurological studies debunked the myth of left-brain right-brain dominance?",type:"interrogative",sub:"tag",level:"advanced",cn:"最近的神经学研究不是已经推翻了左右脑主导的迷信吗？"},
  {id:63,text:"How should multinational corporations balance profitability with corporate social responsibility?",type:"interrogative",sub:"special",level:"advanced",cn:"跨国公司应如何平衡盈利能力与企业社会责任？"},
  {id:64,text:"What are the ethical boundaries of surveillance technology in democratic societies?",type:"interrogative",sub:"special",level:"advanced",cn:"民主社会中监控技术的伦理边界在哪里？"},
  {id:65,text:"Should autonomous vehicles be programmed to prioritize passenger safety or pedestrian safety?",type:"interrogative",sub:"choice",level:"advanced",cn:"自动驾驶车辆应该优先考虑乘客安全还是行人安全？"},

  // ===== DECLARATIVE - ELEMENTARY =====
  {id:100,text:"I like to eat apples.",type:"declarative",sub:"declarative",level:"elementary",cn:"我喜欢吃苹果。"},
  {id:101,text:"The sun is very hot.",type:"declarative",sub:"declarative",level:"elementary",cn:"太阳很热。"},
  {id:102,text:"She is my best friend.",type:"declarative",sub:"declarative",level:"elementary",cn:"她是我最好的朋友。"},
  {id:103,text:"We go to school every day.",type:"declarative",sub:"declarative",level:"elementary",cn:"我们每天去上学。"},
  {id:104,text:"My dog is very cute.",type:"declarative",sub:"declarative",level:"elementary",cn:"我的狗很可爱。"},
  {id:105,text:"It is cold outside.",type:"declarative",sub:"declarative",level:"elementary",cn:"外面很冷。"},
  {id:106,text:"I have two brothers.",type:"declarative",sub:"declarative",level:"elementary",cn:"我有两个兄弟。"},
  {id:107,text:"The cat is sleeping on the sofa.",type:"declarative",sub:"declarative",level:"elementary",cn:"猫在沙发上睡觉。"},
  {id:108,text:"Today is Monday.",type:"declarative",sub:"declarative",level:"elementary",cn:"今天是星期一。"},
  {id:109,text:"I drink milk every morning.",type:"declarative",sub:"declarative",level:"elementary",cn:"我每天早上喝牛奶。"},
  {id:110,text:"She plays the piano very well.",type:"declarative",sub:"declarative",level:"elementary",cn:"她钢琴弹得很好。"},
  {id:111,text:"We live in a big city.",type:"declarative",sub:"declarative",level:"elementary",cn:"我们住在一个大城市。"},
  {id:112,text:"He goes to the park after school.",type:"declarative",sub:"declarative",level:"elementary",cn:"他放学后去公园。"},
  {id:113,text:"My mother cooks dinner every evening.",type:"declarative",sub:"declarative",level:"elementary",cn:"我妈妈每天晚上做晚饭。"},
  {id:114,text:"The flowers are beautiful.",type:"declarative",sub:"declarative",level:"elementary",cn:"花很漂亮。"},
  {id:115,text:"I read books before bed.",type:"declarative",sub:"declarative",level:"elementary",cn:"我睡前看书。"},
  {id:116,text:"They are playing in the garden.",type:"declarative",sub:"declarative",level:"elementary",cn:"他们在花园里玩。"},
  {id:117,text:"The water is very clean.",type:"declarative",sub:"declarative",level:"elementary",cn:"水很干净。"},
  {id:118,text:"I want to be a doctor.",type:"declarative",sub:"declarative",level:"elementary",cn:"我想成为一名医生。"},
  {id:119,text:"The movie was really funny.",type:"declarative",sub:"declarative",level:"elementary",cn:"那部电影真的很搞笑。"},
  {id:120,text:"Birds can fly in the sky.",type:"declarative",sub:"declarative",level:"elementary",cn:"鸟能在天空中飞翔。"},
  {id:121,text:"I like drawing pictures.",type:"declarative",sub:"declarative",level:"elementary",cn:"我喜欢画画。"},
  {id:122,text:"She wears a red dress.",type:"declarative",sub:"declarative",level:"elementary",cn:"她穿着一条红色的裙子。"},
  {id:123,text:"We had pizza for lunch.",type:"declarative",sub:"declarative",level:"elementary",cn:"我们午饭吃了披萨。"},
  {id:124,text:"The train arrives at nine o'clock.",type:"declarative",sub:"declarative",level:"elementary",cn:"火车九点到达。"},

  // ===== DECLARATIVE - INTERMEDIATE =====
  {id:125,text:"Learning a foreign language opens up a world of opportunities.",type:"declarative",sub:"declarative",level:"intermediate",cn:"学习外语会打开一个充满机会的世界。"},
  {id:126,text:"The company has been experiencing steady growth for the past five years.",type:"declarative",sub:"declarative",level:"intermediate",cn:"这家公司过去五年一直在稳步增长。"},
  {id:127,text:"Regular exercise significantly reduces the risk of heart disease.",type:"declarative",sub:"declarative",level:"intermediate",cn:"定期锻炼显著降低患心脏病的风险。"},
  {id:128,text:"Climate change is one of the most pressing challenges of our time.",type:"declarative",sub:"declarative",level:"intermediate",cn:"气候变化是我们时代最紧迫的挑战之一。"},
  {id:129,text:"The meeting has been rescheduled to next Thursday afternoon.",type:"declarative",sub:"declarative",level:"intermediate",cn:"会议已重新安排到下周四下午。"},
  {id:130,text:"She decided to pursue a career in environmental science.",type:"declarative",sub:"declarative",level:"intermediate",cn:"她决定从事环境科学事业。"},
  {id:131,text:"The new software update includes several important security patches.",type:"declarative",sub:"declarative",level:"intermediate",cn:"新的软件更新包含几个重要的安全补丁。"},
  {id:132,text:"They have been working on this project since January.",type:"declarative",sub:"declarative",level:"intermediate",cn:"他们从一月份开始就一直在做这个项目。"},
  {id:133,text:"Good communication skills are essential for professional success.",type:"declarative",sub:"declarative",level:"intermediate",cn:"良好的沟通技巧对职业成功至关重要。"},
  {id:134,text:"The research findings suggest a strong correlation between sleep and productivity.",type:"declarative",sub:"declarative",level:"intermediate",cn:"研究结果表明睡眠和生产力之间有很强的相关性。"},
  {id:135,text:"Public transportation is becoming more efficient in many major cities.",type:"declarative",sub:"declarative",level:"intermediate",cn:"许多大城市的公共交通正变得越来越高效。"},
  {id:136,text:"He realized that time management was the key to balancing work and life.",type:"declarative",sub:"declarative",level:"intermediate",cn:"他意识到时间管理是平衡工作和生活的关键。"},
  {id:137,text:"The restaurant on the corner serves the best pasta in town.",type:"declarative",sub:"declarative",level:"intermediate",cn:"街角的那家餐厅供应全城最好的意面。"},
  {id:138,text:"Technology continues to transform the way we interact with each other.",type:"declarative",sub:"declarative",level:"intermediate",cn:"技术继续改变着我们彼此互动的方式。"},
  {id:139,text:"Many students find it helpful to study in groups rather than alone.",type:"declarative",sub:"declarative",level:"intermediate",cn:"许多学生发现小组学习比独自学习更有帮助。"},

  // ===== DECLARATIVE - ADVANCED =====
  {id:140,text:"The proliferation of artificial intelligence has fundamentally altered the landscape of modern industry.",type:"declarative",sub:"declarative",level:"advanced",cn:"人工智能的普及从根本上改变了现代工业的格局。"},
  {id:141,text:"Neuroplasticity demonstrates that the human brain is far more adaptable than previously believed.",type:"declarative",sub:"declarative",level:"advanced",cn:"神经可塑性表明人脑比以前认为的更具适应性。"},
  {id:142,text:"The socioeconomic ramifications of the pandemic will reverberate for decades to come.",type:"declarative",sub:"declarative",level:"advanced",cn:"这次大流行的社会经济后果将在未来几十年内持续影响。"},
  {id:143,text:"Interdisciplinary collaboration has become increasingly indispensable in addressing complex global challenges.",type:"declarative",sub:"declarative",level:"advanced",cn:"跨学科合作在应对复杂的全球挑战中变得越来越不可或缺。"},
  {id:144,text:"The erosion of biodiversity poses an existential threat to the integrity of global ecosystems.",type:"declarative",sub:"declarative",level:"advanced",cn:"生物多样性的丧失对全球生态系统的完整性构成了生存威胁。"},
  {id:145,text:"Contemporary philosophical discourse increasingly grapples with the ethical implications of biotechnology.",type:"declarative",sub:"declarative",level:"advanced",cn:"当代哲学论述日益关注生物技术的伦理影响。"},
  {id:146,text:"Cognitive behavioral therapy has emerged as one of the most empirically validated psychotherapeutic approaches.",type:"declarative",sub:"declarative",level:"advanced",cn:"认知行为疗法已成为最具实证验证的心理治疗方法之一。"},
  {id:147,text:"The geopolitical tensions in the region have intensified due to competing territorial claims.",type:"declarative",sub:"declarative",level:"advanced",cn:"该地区因领土争端竞争加剧，地缘政治紧张局势加剧。"},
  {id:148,text:"Sustainable development requires a paradigm shift in how societies conceptualize economic progress.",type:"declarative",sub:"declarative",level:"advanced",cn:"可持续发展需要社会在如何看待经济增长方面进行范式转变。"},
  {id:149,text:"The democratization of information through digital platforms has both empowered and polarized public discourse.",type:"declarative",sub:"declarative",level:"advanced",cn:"通过数字平台实现信息民主化，既赋予了公众力量，也使公共话语两极化。"},
  {id:150,text:"Epigenetic research has revealed that environmental factors can influence gene expression across generations.",type:"declarative",sub:"declarative",level:"advanced",cn:"表观遗传学研究揭示了环境因素可以跨代影响基因表达。"},
  {id:151,text:"The implementation of blockchain technology promises to revolutionize supply chain transparency.",type:"declarative",sub:"declarative",level:"advanced",cn:"区块链技术的实施有望彻底改变供应链的透明度。"},

  // ===== IMPERATIVE - ELEMENTARY =====
  {id:200,text:"Please open the door.",type:"declarative",sub:"imperative",level:"elementary",cn:"请开门。"},
  {id:201,text:"Sit down, please.",type:"declarative",sub:"imperative",level:"elementary",cn:"请坐。"},
  {id:202,text:"Close the window.",type:"declarative",sub:"imperative",level:"elementary",cn:"关上窗户。"},
  {id:203,text:"Listen to me carefully.",type:"declarative",sub:"imperative",level:"elementary",cn:"仔细听我说。"},
  {id:204,text:"Turn off the light.",type:"declarative",sub:"imperative",level:"elementary",cn:"关灯。"},
  {id:205,text:"Write your name here.",type:"declarative",sub:"imperative",level:"elementary",cn:"在这里写上你的名字。"},
  {id:206,text:"Come here quickly.",type:"declarative",sub:"imperative",level:"elementary",cn:"快过来。"},
  {id:207,text:"Be quiet in the library.",type:"declarative",sub:"imperative",level:"elementary",cn:"在图书馆里要安静。"},
  {id:208,text:"Wash your hands before eating.",type:"declarative",sub:"imperative",level:"elementary",cn:"吃饭前洗手。"},
  {id:209,text:"Don't run in the hallway.",type:"declarative",sub:"imperative",level:"elementary",cn:"不要在走廊里跑。"},
  {id:210,text:"Give me the book.",type:"declarative",sub:"imperative",level:"elementary",cn:"把书给我。"},
  {id:211,text:"Stand up straight.",type:"declarative",sub:"imperative",level:"elementary",cn:"站直了。"},
  {id:212,text:"Clean your room.",type:"declarative",sub:"imperative",level:"elementary",cn:"打扫你的房间。"},

  // ===== IMPERATIVE - INTERMEDIATE =====
  {id:213,text:"Make sure you submit the report before the deadline.",type:"declarative",sub:"imperative",level:"intermediate",cn:"确保你在截止日期前提交报告。"},
  {id:214,text:"Always double-check your work before handing it in.",type:"declarative",sub:"imperative",level:"intermediate",cn:"交作业前务必仔细检查。"},
  {id:215,text:"Try to maintain a positive attitude even during challenging times.",type:"declarative",sub:"imperative",level:"intermediate",cn:"即使在困难时期也要保持积极态度。"},
  {id:216,text:"Consider all the options before making a final decision.",type:"declarative",sub:"imperative",level:"intermediate",cn:"在做最终决定前考虑所有选项。"},
  {id:217,text:"Take a deep breath and relax before the presentation.",type:"declarative",sub:"imperative",level:"intermediate",cn:"演讲前深呼吸放松一下。"},
  {id:218,text:"Remember to back up your files regularly.",type:"declarative",sub:"imperative",level:"intermediate",cn:"记得定期备份你的文件。"},

  // ===== IMPERATIVE - ADVANCED =====
  {id:219,text:"Endeavor to cultivate intellectual humility in all your academic pursuits.",type:"declarative",sub:"imperative",level:"advanced",cn:"在所有学术追求中努力培养知识上的谦逊。"},
  {id:220,text:"Scrutinize the methodology before drawing any conclusions from the data.",type:"declarative",sub:"imperative",level:"advanced",cn:"在从数据中得出结论之前，仔细审查方法论。"},
  {id:221,text:"Refrain from making premature judgments without thoroughly evaluating the evidence.",type:"declarative",sub:"imperative",level:"advanced",cn:"在没有彻底评估证据之前不要过早下结论。"},

  // ===== EXCLAMATORY - ELEMENTARY =====
  {id:300,text:"What a beautiful day!",type:"declarative",sub:"exclamatory",level:"elementary",cn:"多么美好的一天！"},
  {id:301,text:"How amazing this place is!",type:"declarative",sub:"exclamatory",level:"elementary",cn:"这个地方多么令人惊叹！"},
  {id:302,text:"What a surprise!",type:"declarative",sub:"exclamatory",level:"elementary",cn:"真是个惊喜！"},
  {id:303,text:"How wonderful!",type:"declarative",sub:"exclamatory",level:"elementary",cn:"太棒了！"},
  {id:304,text:"That was so much fun!",type:"declarative",sub:"exclamatory",level:"elementary",cn:"那太有趣了！"},
  {id:305,text:"What a cute puppy!",type:"declarative",sub:"exclamatory",level:"elementary",cn:"多可爱的小狗！"},
  {id:306,text:"I can not believe it!",type:"declarative",sub:"exclamatory",level:"elementary",cn:"我简直不敢相信！"},
  {id:307,text:"How delicious this cake is!",type:"declarative",sub:"exclamatory",level:"elementary",cn:"这蛋糕多美味！"},
  {id:308,text:"What a great idea!",type:"declarative",sub:"exclamatory",level:"elementary",cn:"多好的主意！"},
  {id:309,text:"That is incredible!",type:"declarative",sub:"exclamatory",level:"elementary",cn:"太不可思议了！"},

  // ===== EXCLAMATORY - INTERMEDIATE =====
  {id:310,text:"What an extraordinary performance that was!",type:"declarative",sub:"exclamatory",level:"intermediate",cn:"那是多么精彩的表演！"},
  {id:311,text:"How remarkable it is that technology has come so far!",type:"declarative",sub:"exclamatory",level:"intermediate",cn:"科技发展到如此程度真是太了不起了！"},
  {id:312,text:"What a tremendous achievement for the entire team!",type:"declarative",sub:"exclamatory",level:"intermediate",cn:"这对整个团队来说是多么巨大的成就！"},
  {id:313,text:"How inspiring it is to see young people making a difference!",type:"declarative",sub:"exclamatory",level:"intermediate",cn:"看到年轻人做出改变真是太鼓舞人心了！"},
  {id:314,text:"What a relief that everything worked out in the end!",type:"declarative",sub:"exclamatory",level:"intermediate",cn:"最后一切都好了，真是松了口气！"},
  {id:315,text:"How beautifully she played that piece!",type:"declarative",sub:"exclamatory",level:"intermediate",cn:"她把那首曲子演奏得多么优美！"},

  // ===== EXCLAMATORY - ADVANCED =====
  {id:316,text:"What an unprecedented paradigm shift this discovery represents!",type:"declarative",sub:"exclamatory",level:"advanced",cn:"这一发现代表了一个前所未有的范式转变！"},
  {id:317,text:"How profoundly the digital revolution has transformed contemporary society!",type:"declarative",sub:"exclamatory",level:"advanced",cn:"数字革命如此深刻地改变了当代社会！"},
  {id:318,text:"What a monumental breakthrough in renewable energy technology!",type:"declarative",sub:"exclamatory",level:"advanced",cn:"可再生能源技术的一个里程碑式突破！"},

  // ===== DIALOGUE - ELEMENTARY =====
  {id:1001,text:"A: Excuse me, I am looking for the downtown library. Could you please show me the fastest way to get there?",type:"dialogue",sub:"conversation",level:"elementary",cn:"A：打扰一下，我在找市中心的图书馆。你能告诉我到那里最快的路线吗？"},
  {id:1002,text:"B: Of course. You need to walk straight down this street for about three blocks, and then turn right at the traffic light.",type:"dialogue",sub:"conversation",level:"elementary",cn:"B：当然。你需要沿着这条街一直走大概三个街区，然后在红绿灯处右转。"},
  {id:1003,text:"A: Thank you so much! Is it within walking distance, or should I take a bus from here?",type:"dialogue",sub:"conversation",level:"elementary",cn:"A：非常感谢！走着去就能到吗，还是我应该从这里坐公交车？"},
  {id:1004,text:"B: It is perfectly walkable. It should only take you about ten minutes if you keep a good walking pace.",type:"dialogue",sub:"conversation",level:"elementary",cn:"B：完全走得过去。如果你保持一个比较好的步行速度，大约只需要十分钟。"},

  // ===== DIALOGUE - INTERMEDIATE =====
  {id:1005,text:"A: Have you had a chance to thoroughly review the updated project proposal I sent to you yesterday afternoon?",type:"dialogue",sub:"conversation",level:"intermediate",cn:"A：你昨天下午有没有抽出时间，仔细审阅一下我发给你的那份更新后的项目提案？"},
  {id:1006,text:"B: Yes, I went through the entire document. However, I noticed that we might have underestimated the overall budget required for the third phase.",type:"dialogue",sub:"conversation",level:"intermediate",cn:"B：是的，我把整个文件都看了一遍。不过我注意到，我们似乎低估了第三阶段所需的整体预算。"},
  {id:1007,text:"A: That is a very valid concern. I was actually planning to schedule a comprehensive meeting with the finance department to discuss potential adjustments.",type:"dialogue",sub:"conversation",level:"intermediate",cn:"A：你的担忧非常有道理。我实际上正打算和财务部预约一个全面的会议，来讨论一下如何进行潜在的调整。"},
  {id:1008,text:"B: That sounds like an excellent strategy. Let me know when the meeting starts, and I will make sure to bring my detailed cost analysis presentation.",type:"dialogue",sub:"conversation",level:"intermediate",cn:"B：听起来是个非常好的策略。会议开始的时候告诉我一声，我一定会带上我那份详细的成本分析演示文稿。"},
  
  // ===== DIALOGUE - ADVANCED =====
  {id:1009,text:"A: What is your comprehensive perspective on integrating decentralized synthetic assets into the traditionally heavily regulated banking sector?",type:"dialogue",sub:"conversation",level:"advanced",cn:"A：关于将去中心化的合成资产整合到传统受到严格监管的银行业务中，你比较全面的看法是什么？"},
  {id:1010,text:"B: Fundamentally, I argue that while the technological efficiency gains are absolutely undeniable, doing so inevitably introduces an array of unprecedented regulatory frictions.",type:"dialogue",sub:"conversation",level:"advanced",cn:"B：从根本上说，我认为虽然技术效率的提升是毫无疑问的，但这样做不可避免地会引入一系列前所未有的监管摩擦。"},
  {id:1011,text:"A: That is ostensibly true, yet ignoring such a significant paradigm shift could arguably render orthodox financial institutions obsolete within the next decade.",type:"dialogue",sub:"conversation",level:"advanced",cn:"A：这表面上看是真的，但如果不去理会这样重大的范式转变，可以说在未来十年内会让正统的金融机构彻底被时代淘汰。"},
  {id:1012,text:"B: Precisely. This is why cultivating a harmonious framework that perfectly bridges cryptographically secured ledgers with conservative risk-mitigation strategies is absolutely imperative.",type:"dialogue",sub:"conversation",level:"advanced",cn:"B：恰恰如此。这就是为什么我们绝对有必要去培养一个和谐的框架，以此将受到密码学保护的账本与保守的风险缓解策略完美地桥接起来。"}
];

// ==================== WORD DICTIONARY ====================
const DICTIONARY = {
  "name":{ipa:"/neɪm/",pos:"n.",cn:"名字",ex:["What is your name?","She has a beautiful name."]},
  "help":{ipa:"/hɛlp/",pos:"v./n.",cn:"帮助",ex:["Can you help me?","I need some help."]},
  "like":{ipa:"/laɪk/",pos:"v./prep.",cn:"喜欢；像",ex:["I like coffee.","She looks like her mother."]},
  "coffee":{ipa:"/ˈkɒfi/",pos:"n.",cn:"咖啡",ex:["Do you like coffee?","I drink coffee every morning."]},
  "time":{ipa:"/taɪm/",pos:"n.",cn:"时间",ex:["What time is it?","Time flies so fast."]},
  "book":{ipa:"/bʊk/",pos:"n.",cn:"书",ex:["Is this your book?","I read a book yesterday."]},
  "water":{ipa:"/ˈwɔːtər/",pos:"n.",cn:"水",ex:["Can I have some water?","The water is clean."]},
  "food":{ipa:"/fuːd/",pos:"n.",cn:"食物",ex:["What is your favorite food?","This food is delicious."]},
  "school":{ipa:"/skuːl/",pos:"n.",cn:"学校",ex:["We go to school every day.","The school is near my house."]},
  "friend":{ipa:"/frɛnd/",pos:"n.",cn:"朋友",ex:["She is my best friend.","I met a new friend today."]},
  "beautiful":{ipa:"/ˈbjuːtɪfəl/",pos:"adj.",cn:"美丽的",ex:["What a beautiful day!","The flowers are beautiful."]},
  "happy":{ipa:"/ˈhæpi/",pos:"adj.",cn:"快乐的",ex:["What makes you happy?","I feel very happy today."]},
  "language":{ipa:"/ˈlæŋɡwɪdʒ/",pos:"n.",cn:"语言",ex:["Learning a foreign language is important.","English is a global language."]},
  "technology":{ipa:"/tɛkˈnɒlədʒi/",pos:"n.",cn:"技术",ex:["Technology is changing rapidly.","We rely on technology every day."]},
  "exercise":{ipa:"/ˈɛksərsaɪz/",pos:"n./v.",cn:"锻炼；练习",ex:["Regular exercise is good for health.","How often do you exercise?"]},
  "career":{ipa:"/kəˈrɪr/",pos:"n.",cn:"职业；事业",ex:["She decided to change her career.","He has a successful career."]},
  "experience":{ipa:"/ɪkˈspɪriəns/",pos:"n.",cn:"经验；经历",ex:["She has ten years of experience.","It was an amazing experience."]},
  "environment":{ipa:"/ɪnˈvaɪrənmənt/",pos:"n.",cn:"环境",ex:["We must protect the environment.","The work environment is friendly."]},
  "economy":{ipa:"/ɪˈkɒnəmi/",pos:"n.",cn:"经济",ex:["The global economy is growing.","We need a strong economy."]},
  "intelligence":{ipa:"/ɪnˈtɛlɪdʒəns/",pos:"n.",cn:"智力；情报",ex:["Artificial intelligence is advancing.","He shows great intelligence."]},
  "sustainable":{ipa:"/səˈsteɪnəbl/",pos:"adj.",cn:"可持续的",ex:["Sustainable energy is the future.","We need sustainable development."]},
  "paradigm":{ipa:"/ˈpærəˌdaɪm/",pos:"n.",cn:"范式；典范",ex:["A paradigm shift has occurred.","The old paradigm no longer works."]},
  "philosophy":{ipa:"/fɪˈlɒsəfi/",pos:"n.",cn:"哲学",ex:["She studies philosophy at university.","His philosophy of life is simple."]},
  "research":{ipa:"/rɪˈsɜːrtʃ/",pos:"n./v.",cn:"研究",ex:["The research findings are promising.","She researches climate change."]},
  "education":{ipa:"/ˌɛdʒuˈkeɪʃən/",pos:"n.",cn:"教育",ex:["Education is very important.","She works in education."]},
  "opportunity":{ipa:"/ˌɒpərˈtjuːnɪti/",pos:"n.",cn:"机会",ex:["This is a great opportunity.","Opportunities come to those who work hard."]},
  "communication":{ipa:"/kəˌmjuːnɪˈkeɪʃən/",pos:"n.",cn:"交流；通讯",ex:["Good communication is essential.","Communication skills matter."]},
  "society":{ipa:"/səˈsaɪəti/",pos:"n.",cn:"社会",ex:["We live in a complex society.","Society is always changing."]},
  "decision":{ipa:"/dɪˈsɪʒən/",pos:"n.",cn:"决定",ex:["Making decisions is hard.","It was a difficult decision."]},
  "challenge":{ipa:"/ˈtʃælɪndʒ/",pos:"n./v.",cn:"挑战",ex:["Climate change is a big challenge.","She challenged herself."]},
  "discover":{ipa:"/dɪsˈkʌvər/",pos:"v.",cn:"发现",ex:["Scientists discover new species.","He discovered his passion."]},
  "important":{ipa:"/ɪmˈpɔːrtənt/",pos:"adj.",cn:"重要的",ex:["This is very important.","Education is important."]},
  "different":{ipa:"/ˈdɪfərənt/",pos:"adj.",cn:"不同的",ex:["We have different opinions.","Each person is different."]},
  "understand":{ipa:"/ˌʌndərˈstænd/",pos:"v.",cn:"理解",ex:["Do you understand me?","I understand the problem now."]},
  "remember":{ipa:"/rɪˈmɛmbər/",pos:"v.",cn:"记住",ex:["Remember to call me.","I remember that day clearly."]},
  "practice":{ipa:"/ˈpræktɪs/",pos:"n./v.",cn:"练习；实践",ex:["Practice makes perfect.","She practices piano daily."]},
  "success":{ipa:"/səkˈsɛs/",pos:"n.",cn:"成功",ex:["Hard work leads to success.","The project was a great success."]},
  "change":{ipa:"/tʃeɪndʒ/",pos:"v./n.",cn:"改变；变化",ex:["Change is inevitable.","We need to change our approach."]},
  "world":{ipa:"/wɜːrld/",pos:"n.",cn:"世界",ex:["The world is vast.","She wants to travel the world."]},
  "people":{ipa:"/ˈpiːpl/",pos:"n.",cn:"人们",ex:["Many people live here.","People are generally kind."]},
  "think":{ipa:"/θɪŋk/",pos:"v.",cn:"想；认为",ex:["What do you think?","I think it is a good idea."]},
  "learn":{ipa:"/lɜːrn/",pos:"v.",cn:"学习",ex:["I want to learn English.","We learn from our mistakes."]},
  "work":{ipa:"/wɜːrk/",pos:"v./n.",cn:"工作",ex:["I work in an office.","Hard work pays off."]},
  "play":{ipa:"/pleɪ/",pos:"v./n.",cn:"玩；演奏",ex:["Do you want to play?","She plays violin beautifully."]},
  "read":{ipa:"/riːd/",pos:"v.",cn:"阅读",ex:["I read books every day.","She reads very fast."]},
  "write":{ipa:"/raɪt/",pos:"v.",cn:"写",ex:["Write your name here.","She writes poems."]},
  "open":{ipa:"/ˈoʊpən/",pos:"v./adj.",cn:"打开；开放的",ex:["Please open the door.","The store is open."]},
  "close":{ipa:"/kloʊz/",pos:"v./adj.",cn:"关闭；近的",ex:["Close the window.","My house is close to school."]},
  "big":{ipa:"/bɪɡ/",pos:"adj.",cn:"大的",ex:["We live in a big city.","That is a big house."]},
  "small":{ipa:"/smɔːl/",pos:"adj.",cn:"小的",ex:["She has a small dog.","The room is very small."]},
  "good":{ipa:"/ɡʊd/",pos:"adj.",cn:"好的",ex:["Good morning!","This is a good book."]},
  "new":{ipa:"/njuː/",pos:"adj.",cn:"新的",ex:["I bought a new phone.","She started a new job."]},
  "old":{ipa:"/oʊld/",pos:"adj.",cn:"旧的；老的",ex:["How old are you?","That is an old building."]},
  "day":{ipa:"/deɪ/",pos:"n.",cn:"天；白天",ex:["What a beautiful day!","Today is a good day."]},
  "morning":{ipa:"/ˈmɔːrnɪŋ/",pos:"n.",cn:"早晨",ex:["Good morning!","I wake up early in the morning."]},
  "night":{ipa:"/naɪt/",pos:"n.",cn:"夜晚",ex:["Good night!","The stars shine at night."]},
  "today":{ipa:"/təˈdeɪ/",pos:"adv./n.",cn:"今天",ex:["How are you today?","Today is Monday."]},
  "year":{ipa:"/jɪr/",pos:"n.",cn:"年",ex:["Happy new year!","She is ten years old."]},
  "house":{ipa:"/haʊs/",pos:"n.",cn:"房子",ex:["I live in a big house.","The house is very old."]},
  "city":{ipa:"/ˈsɪti/",pos:"n.",cn:"城市",ex:["We live in a big city.","The city is very beautiful."]},
  "family":{ipa:"/ˈfæməli/",pos:"n.",cn:"家庭",ex:["I love my family.","Family is important."]},
  "mother":{ipa:"/ˈmʌðər/",pos:"n.",cn:"母亲",ex:["My mother is a teacher.","She loves her mother."]},
  "father":{ipa:"/ˈfɑːðər/",pos:"n.",cn:"父亲",ex:["My father works in a bank.","He is a good father."]},
  "student":{ipa:"/ˈstjuːdənt/",pos:"n.",cn:"学生",ex:["She is a good student.","Many students study here."]},
  "teacher":{ipa:"/ˈtiːtʃər/",pos:"n.",cn:"老师",ex:["Who is your teacher?","The teacher is very kind."]},
  "doctor":{ipa:"/ˈdɒktər/",pos:"n.",cn:"医生",ex:["I want to be a doctor.","She went to see the doctor."]},
  "music":{ipa:"/ˈmjuːzɪk/",pos:"n.",cn:"音乐",ex:["I love listening to music.","She studies music."]},
  "movie":{ipa:"/ˈmuːvi/",pos:"n.",cn:"电影",ex:["The movie was really funny.","Let us watch a movie."]},
  "color":{ipa:"/ˈkʌlər/",pos:"n.",cn:"颜色",ex:["What color do you like?","My favorite color is blue."]},
  "garden":{ipa:"/ˈɡɑːrdən/",pos:"n.",cn:"花园",ex:["They play in the garden.","The garden is full of flowers."]},
  "rain":{ipa:"/reɪn/",pos:"n./v.",cn:"雨；下雨",ex:["Is it raining outside?","The rain stopped."]},
  "sun":{ipa:"/sʌn/",pos:"n.",cn:"太阳",ex:["The sun is very hot.","The sun rises in the east."]},
  "planet":{ipa:"/ˈplænɪt/",pos:"n.",cn:"行星",ex:["Earth is our planet.","Mars is the red planet."]},
  "animal":{ipa:"/ˈænɪməl/",pos:"n.",cn:"动物",ex:["Dogs are loyal animals.","I love animals."]},
  "attention":{ipa:"/əˈtɛnʃən/",pos:"n.",cn:"注意力",ex:["Pay attention to the lecture.","She needs attention."]},
  "government":{ipa:"/ˈɡʌvərnmənt/",pos:"n.",cn:"政府",ex:["The government passed a new law.","Government policy affects everyone."]},
  "development":{ipa:"/dɪˈvɛləpmənt/",pos:"n.",cn:"发展",ex:["Economic development is important.","Software development requires skill."]},
  "information":{ipa:"/ˌɪnfərˈmeɪʃən/",pos:"n.",cn:"信息",ex:["I need more information.","Information spreads quickly online."]},
  "knowledge":{ipa:"/ˈnɒlɪdʒ/",pos:"n.",cn:"知识",ex:["Knowledge is power.","She has broad knowledge."]},
  "problem":{ipa:"/ˈprɒbləm/",pos:"n.",cn:"问题",ex:["We need to solve this problem.","No problem!"]},
  "question":{ipa:"/ˈkwɛstʃən/",pos:"n.",cn:"问题",ex:["Do you have any questions?","That is a good question."]},
  "answer":{ipa:"/ˈænsər/",pos:"n./v.",cn:"回答",ex:["What is the answer?","Please answer the question."]},
  "what":{ipa:"/wɒt/",pos:"pron./det.",cn:"什么",ex:["What is your name?","What time is it?"]},
  "how":{ipa:"/haʊ/",pos:"adv.",cn:"如何；怎样",ex:["How are you?","How much does it cost?"]},
  "where":{ipa:"/wɛr/",pos:"adv.",cn:"哪里",ex:["Where do you live?","Where is the station?"]},
  "when":{ipa:"/wɛn/",pos:"adv.",cn:"什么时候",ex:["When is your birthday?","When did you arrive?"]},
  "who":{ipa:"/huː/",pos:"pron.",cn:"谁",ex:["Who is your teacher?","Who are you?"]},
  "why":{ipa:"/waɪ/",pos:"adv.",cn:"为什么",ex:["Why are you late?","Why did you do that?"]},
  "is":{ipa:"/ɪz/",pos:"v.",cn:"是（be的第三人称单数）",ex:["What is your name?","She is my friend."]},
  "are":{ipa:"/ɑːr/",pos:"v.",cn:"是（be的复数形式）",ex:["How are you?","They are playing."]},
  "do":{ipa:"/duː/",pos:"v.",cn:"做",ex:["Do you like coffee?","What do you do?"]},
  "can":{ipa:"/kæn/",pos:"v.",cn:"能；可以",ex:["Can you help me?","I can swim."]},
  "have":{ipa:"/hæv/",pos:"v.",cn:"有",ex:["I have two brothers.","Have you been there?"]},
  "the":{ipa:"/ðə/",pos:"art.",cn:"这；那（定冠词）",ex:["The sun is hot.","Close the door."]},
  "a":{ipa:"/ə/",pos:"art.",cn:"一个（不定冠词）",ex:["She is a doctor.","I want a book."]},
  "this":{ipa:"/ðɪs/",pos:"pron./det.",cn:"这；这个",ex:["Is this your book?","This is my house."]},
  "that":{ipa:"/ðæt/",pos:"pron./det.",cn:"那；那个",ex:["That was great!","I know that."]},
  "it":{ipa:"/ɪt/",pos:"pron.",cn:"它",ex:["It is cold outside.","I like it."]},
  "you":{ipa:"/juː/",pos:"pron.",cn:"你；你们",ex:["How are you?","Thank you!"]},
  "i":{ipa:"/aɪ/",pos:"pron.",cn:"我",ex:["I like coffee.","I am a student."]},
  "she":{ipa:"/ʃiː/",pos:"pron.",cn:"她",ex:["She is my friend.","She plays piano."]},
  "he":{ipa:"/hiː/",pos:"pron.",cn:"他",ex:["He is a teacher.","He goes to school."]},
  "we":{ipa:"/wiː/",pos:"pron.",cn:"我们",ex:["We go to school.","We live in a city."]},
  "they":{ipa:"/ðeɪ/",pos:"pron.",cn:"他们",ex:["They are playing.","They live here."]},
  "my":{ipa:"/maɪ/",pos:"det.",cn:"我的",ex:["My name is Tom.","My dog is cute."]},
  "your":{ipa:"/jɔːr/",pos:"det.",cn:"你的",ex:["What is your name?","Your book is here."]},
  "very":{ipa:"/ˈvɛri/",pos:"adv.",cn:"非常",ex:["The sun is very hot.","She is very kind."]},
  "not":{ipa:"/nɒt/",pos:"adv.",cn:"不",ex:["I do not know.","It is not easy."]},
  "but":{ipa:"/bʌt/",pos:"conj.",cn:"但是",ex:["I like tea but not coffee.","It is small but nice."]},
  "and":{ipa:"/ænd/",pos:"conj.",cn:"和；而且",ex:["You and I are friends.","Read and write."]},
  "or":{ipa:"/ɔːr/",pos:"conj.",cn:"或者",ex:["Tea or coffee?","Do or die."]},
  "every":{ipa:"/ˈɛvri/",pos:"det.",cn:"每一个",ex:["We go to school every day.","Every person is unique."]},
  "some":{ipa:"/sʌm/",pos:"det.",cn:"一些",ex:["Can I have some water?","Some people like rain."]},
  "much":{ipa:"/mʌtʃ/",pos:"det./adv.",cn:"很多；非常",ex:["How much does it cost?","Thank you very much."]},
  "many":{ipa:"/ˈmɛni/",pos:"det.",cn:"许多",ex:["Many people came.","How many do you have?"]},
  "make":{ipa:"/meɪk/",pos:"v.",cn:"做；制作",ex:["Make sure you finish.","She makes cakes."]},
  "take":{ipa:"/teɪk/",pos:"v.",cn:"拿；带",ex:["Take a deep breath.","Take your time."]},
  "go":{ipa:"/ɡoʊ/",pos:"v.",cn:"去",ex:["We go to school.","Let us go!"]},
  "come":{ipa:"/kʌm/",pos:"v.",cn:"来",ex:["Come here quickly.","She comes from China."]},
  "see":{ipa:"/siː/",pos:"v.",cn:"看见",ex:["I can see the mountain.","See you tomorrow."]},
  "give":{ipa:"/ɡɪv/",pos:"v.",cn:"给",ex:["Give me the book.","She gives good advice."]},
  "eat":{ipa:"/iːt/",pos:"v.",cn:"吃",ex:["I like to eat apples.","Let us eat lunch."]},
  "drink":{ipa:"/drɪŋk/",pos:"v./n.",cn:"喝；饮料",ex:["I drink milk every morning.","Would you like a drink?"]},
  "live":{ipa:"/lɪv/",pos:"v.",cn:"生活；居住",ex:["Where do you live?","We live in a city."]},
  "speak":{ipa:"/spiːk/",pos:"v.",cn:"说；讲",ex:["Do you speak English?","She speaks three languages."]},
  "proliferation":{ipa:"/prəˌlɪfəˈreɪʃən/",pos:"n.",cn:"激增；扩散",ex:["The proliferation of AI has changed industry.","Nuclear proliferation is a concern."]},
  "fundamentally":{ipa:"/ˌfʌndəˈmɛntəli/",pos:"adv.",cn:"根本地；从根本上",ex:["This fundamentally changes everything.","They disagree fundamentally."]},
  "artificial":{ipa:"/ˌɑːrtɪˈfɪʃəl/",pos:"adj.",cn:"人造的；人工的",ex:["Artificial intelligence is advancing.","The flowers are artificial."]},
  "altered":{ipa:"/ˈɔːltərd/",pos:"v.",cn:"改变了的",ex:["The landscape has been altered.","She altered the dress."]},
  "landscape":{ipa:"/ˈlændskeɪp/",pos:"n.",cn:"景观；格局",ex:["The landscape is beautiful.","The business landscape is changing."]},
  "modern":{ipa:"/ˈmɒdərn/",pos:"adj.",cn:"现代的",ex:["Modern technology is powerful.","She likes modern art."]},
  "industry":{ipa:"/ˈɪndəstri/",pos:"n.",cn:"工业；行业",ex:["The tech industry is growing.","Heavy industry produces pollution."]},
  "neuroplasticity":{ipa:"/ˌnjʊəroʊplæˈstɪsɪti/",pos:"n.",cn:"神经可塑性",ex:["Neuroplasticity shows the brain can adapt.","Research in neuroplasticity is advancing."]},
  "demonstrates":{ipa:"/ˈdɛmənstreɪts/",pos:"v.",cn:"证明；展示",ex:["This demonstrates the concept clearly.","She demonstrates great skill."]},
  "adaptable":{ipa:"/əˈdæptəbl/",pos:"adj.",cn:"适应性强的",ex:["Humans are highly adaptable.","The plan is adaptable."]},
  "socioeconomic":{ipa:"/ˌsoʊsioʊˌɛkəˈnɒmɪk/",pos:"adj.",cn:"社会经济的",ex:["Socioeconomic factors affect health.","The socioeconomic gap is widening."]},
  "ramifications":{ipa:"/ˌræmɪfɪˈkeɪʃənz/",pos:"n.",cn:"后果；影响",ex:["The ramifications are far-reaching.","Consider the ramifications carefully."]},
  "pandemic":{ipa:"/pænˈdɛmɪk/",pos:"n.",cn:"大流行病",ex:["The pandemic affected millions.","We learned from the pandemic."]},
  "reverberate":{ipa:"/rɪˈvɜːrbəreɪt/",pos:"v.",cn:"回响；持续影响",ex:["The effects will reverberate for years.","Sound reverberates in the hall."]},
  "interdisciplinary":{ipa:"/ˌɪntərˈdɪsɪplɪnɛri/",pos:"adj.",cn:"跨学科的",ex:["Interdisciplinary research is valuable.","She takes an interdisciplinary approach."]},
  "collaboration":{ipa:"/kəˌlæbəˈreɪʃən/",pos:"n.",cn:"合作；协作",ex:["Collaboration leads to innovation.","The project requires collaboration."]},
  "indispensable":{ipa:"/ˌɪndɪˈspɛnsəbl/",pos:"adj.",cn:"不可或缺的",ex:["Technology has become indispensable.","She is indispensable to the team."]},
  "biodiversity":{ipa:"/ˌbaɪoʊdaɪˈvɜːrsɪti/",pos:"n.",cn:"生物多样性",ex:["Biodiversity is declining globally.","We must protect biodiversity."]},
  "erosion":{ipa:"/ɪˈroʊʒən/",pos:"n.",cn:"侵蚀；减少",ex:["Soil erosion is a problem.","The erosion of trust is dangerous."]},
  "existential":{ipa:"/ˌɛɡzɪˈstɛnʃəl/",pos:"adj.",cn:"存在的；关乎存亡的",ex:["Climate change is an existential threat.","She had an existential crisis."]},
  "ecosystem":{ipa:"/ˈiːkoʊsɪstəm/",pos:"n.",cn:"生态系统",ex:["The ecosystem is fragile.","Marine ecosystems are under threat."]},
  "contemporary":{ipa:"/kənˈtɛmpərɛri/",pos:"adj.",cn:"当代的",ex:["Contemporary art is diverse.","She is a contemporary writer."]},
  "cognitive":{ipa:"/ˈkɒɡnɪtɪv/",pos:"adj.",cn:"认知的",ex:["Cognitive skills develop early.","Cognitive therapy is effective."]},
  "empirically":{ipa:"/ɪmˈpɪrɪkəli/",pos:"adv.",cn:"以经验为依据地",ex:["The theory was empirically tested.","Empirically validated methods work best."]},
  "geopolitical":{ipa:"/ˌdʒiːoʊpəˈlɪtɪkəl/",pos:"adj.",cn:"地缘政治的",ex:["Geopolitical tensions are rising.","A geopolitical conflict emerged."]},
  "unprecedented":{ipa:"/ʌnˈprɛsɪdɛntɪd/",pos:"adj.",cn:"前所未有的",ex:["An unprecedented event occurred.","The growth was unprecedented."]},
  "monumental":{ipa:"/ˌmɒnjuˈmɛntəl/",pos:"adj.",cn:"里程碑式的；巨大的",ex:["A monumental breakthrough was made.","The task was monumental."]},
  "breakthrough":{ipa:"/ˈbreɪkθruː/",pos:"n.",cn:"突破",ex:["A scientific breakthrough was announced.","This is a major breakthrough."]},
  "renewable":{ipa:"/rɪˈnjuːəbl/",pos:"adj.",cn:"可再生的",ex:["Renewable energy is important.","Solar is a renewable resource."]},
  "quantum":{ipa:"/ˈkwɒntəm/",pos:"adj./n.",cn:"量子的；量子",ex:["Quantum computing is revolutionary.","A quantum leap in technology."]},
  "globalization":{ipa:"/ˌɡloʊbəlaɪˈzeɪʃən/",pos:"n.",cn:"全球化",ex:["Globalization has connected the world.","The effects of globalization are debated."]},
  "discrimination":{ipa:"/dɪˌskrɪmɪˈneɪʃən/",pos:"n.",cn:"歧视",ex:["Discrimination is unacceptable.","Fight against discrimination."]},
  "surveillance":{ipa:"/sərˈveɪləns/",pos:"n.",cn:"监控",ex:["Surveillance cameras are everywhere.","Mass surveillance raises concerns."]},
  "autonomous":{ipa:"/ɔːˈtɒnəməs/",pos:"adj.",cn:"自主的；自动驾驶的",ex:["Autonomous vehicles are being tested.","The region is autonomous."]},
  "misinformation":{ipa:"/ˌmɪsɪnfərˈmeɪʃən/",pos:"n.",cn:"错误信息",ex:["Misinformation spreads online.","Combat misinformation with facts."]},
  "feasible":{ipa:"/ˈfiːzɪbl/",pos:"adj.",cn:"可行的",ex:["Is this plan feasible?","The project is technically feasible."]},
  "scrutinize":{ipa:"/ˈskruːtɪnaɪz/",pos:"v.",cn:"仔细审查",ex:["Scrutinize the data carefully.","The report was scrutinized."]},
  "endeavor":{ipa:"/ɪnˈdɛvər/",pos:"v./n.",cn:"努力；尝试",ex:["Endeavor to do your best.","It was a worthwhile endeavor."]},
  "cultivate":{ipa:"/ˈkʌltɪveɪt/",pos:"v.",cn:"培养；培育",ex:["Cultivate good habits.","They cultivate rice fields."]},
  "humility":{ipa:"/hjuːˈmɪləti/",pos:"n.",cn:"谦逊；谦虚",ex:["Practice humility in life.","He showed great humility."]},
  "methodology":{ipa:"/ˌmɛθəˈdɒlədʒi/",pos:"n.",cn:"方法论",ex:["The research methodology was sound.","We need a clear methodology."]},
  "refrain":{ipa:"/rɪˈfreɪn/",pos:"v.",cn:"克制；避免",ex:["Refrain from making judgments.","Please refrain from smoking."]},
  "premature":{ipa:"/ˌprɛməˈtjʊr/",pos:"adj.",cn:"过早的；仓促的",ex:["A premature conclusion was drawn.","The baby was premature."]},
  "correlation":{ipa:"/ˌkɒrəˈleɪʃən/",pos:"n.",cn:"相关性",ex:["There is a strong correlation.","Correlation does not imply causation."]},
  "productive":{ipa:"/prəˈdʌktɪv/",pos:"adj.",cn:"高效的；多产的",ex:["The meeting was very productive.","She is a productive writer."]},
  "incredible":{ipa:"/ɪnˈkrɛdɪbl/",pos:"adj.",cn:"难以置信的；极好的",ex:["That is incredible!","She did an incredible job."]},
  "amazing":{ipa:"/əˈmeɪzɪŋ/",pos:"adj.",cn:"令人惊叹的",ex:["How amazing this place is!","The show was amazing."]},
  "wonderful":{ipa:"/ˈwʌndərfəl/",pos:"adj.",cn:"极好的；精彩的",ex:["How wonderful!","We had a wonderful time."]},
  "surprise":{ipa:"/sərˈpraɪz/",pos:"n./v.",cn:"惊喜；使惊讶",ex:["What a surprise!","She surprised everyone."]},
  "delicious":{ipa:"/dɪˈlɪʃəs/",pos:"adj.",cn:"美味的",ex:["How delicious this cake is!","The food is delicious."]},
  "cold":{ipa:"/koʊld/",pos:"adj.",cn:"冷的",ex:["It is cold outside.","I feel cold today."]},
  "hot":{ipa:"/hɒt/",pos:"adj.",cn:"热的",ex:["The sun is very hot.","The coffee is too hot."]},
  "clean":{ipa:"/kliːn/",pos:"adj./v.",cn:"干净的；打扫",ex:["The water is clean.","Clean your room."]},
  "listen":{ipa:"/ˈlɪsən/",pos:"v.",cn:"听",ex:["Listen to me carefully.","I love listening to music."]},
  "quiet":{ipa:"/ˈkwaɪət/",pos:"adj.",cn:"安静的",ex:["Be quiet in the library.","The night is very quiet."]},
  "sit":{ipa:"/sɪt/",pos:"v.",cn:"坐",ex:["Sit down, please.","She sat by the window."]},
  "stand":{ipa:"/stænd/",pos:"v.",cn:"站",ex:["Stand up straight.","She stands in line."]},
  "run":{ipa:"/rʌn/",pos:"v.",cn:"跑",ex:["Don't run in the hallway.","She runs every morning."]},
  "walk":{ipa:"/wɔːk/",pos:"v./n.",cn:"走；散步",ex:["It is a beautiful day for a walk.","I walk to school."]},
  "meeting":{ipa:"/ˈmiːtɪŋ/",pos:"n.",cn:"会议",ex:["The meeting was rescheduled.","We have a meeting today."]},
  "report":{ipa:"/rɪˈpɔːrt/",pos:"n./v.",cn:"报告",ex:["Submit the report on time.","She reported the news."]},
  "attitude":{ipa:"/ˈætɪtjuːd/",pos:"n.",cn:"态度",ex:["Maintain a positive attitude.","Her attitude is inspiring."]},
  "consider":{ipa:"/kənˈsɪdər/",pos:"v.",cn:"考虑",ex:["Consider all the options.","I will consider your suggestion."]},
  "breath":{ipa:"/brɛθ/",pos:"n.",cn:"呼吸",ex:["Take a deep breath.","She held her breath."]},
  "relax":{ipa:"/rɪˈlæks/",pos:"v.",cn:"放松",ex:["Relax before the presentation.","Try to relax and enjoy."]},
  "travel":{ipa:"/ˈtrævəl/",pos:"v./n.",cn:"旅行",ex:["She wants to travel the world.","Travel broadens the mind."]},
  "holiday":{ipa:"/ˈhɒlɪdeɪ/",pos:"n.",cn:"假日；假期",ex:["How do you spend your holidays?","We had a great holiday."]},
  "reshape":{ipa:"/riːˈʃeɪp/",pos:"v.",cn:"重塑；改变...的形状",ex:["AI will reshape the global economy.","We must reshape our strategy."]},
  "extent":{ipa:"/ɪkˈstɛnt/",pos:"n.",cn:"程度；范围",ex:["To what extent do you agree?","The extent of the damage is unknown."]},
  "economy":{ipa:"/ɪˈkɒnəmi/",pos:"n.",cn:"经济",ex:["The global economy is interconnected.","They study the local economy."]},
  "global":{ipa:"/ˈɡloʊbəl/",pos:"adj.",cn:"全球的",ex:["Global warming is a crisis.","We operate on a global scale."]},
  "intelligence": { ipa: "/ɪnˈtɛlɪdʒəns/", pos: "n.", cn: "智力；智能", ex: ["Artificial intelligence is evolving.", "He has high intelligence."] },
  // new
  "been": {ipa: "/bɪn/", pos: "v.", cn: "be的过去分词", ex: ["Have you ever been to Japan?", "I have been working all day."]},
  "was": {ipa: "/wəz/", pos: "v.", cn: "be的过去式(单数)", ex: ["The movie was really funny.", "He was a teacher."]},
  "were": {ipa: "/wɜːr/", pos: "v.", cn: "be的过去式(复数)", ex: ["They were playing in the garden.", "You were right."]},
  "be": {ipa: "/biː/", pos: "v.", cn: "是；被", ex: ["To be or not to be.", "I want to be a doctor."]},
  "had": {ipa: "/hæd/", pos: "v.", cn: "have的过去式/过去分词", ex: ["I had pizza for lunch.", "They had finished the project."]},
  "has": {ipa: "/hæz/", pos: "v.", cn: "have的第三人称单数", ex: ["She has two brothers.", "He has been busy."]},
  "did": {ipa: "/dɪd/", pos: "v.", cn: "do的过去式", ex: ["Why did you decide to change?", "I did my homework."]},
  "does": {ipa: "/dʌz/", pos: "v.", cn: "do的第三人称单数", ex: ["How much does it cost?", "She does her best."]},
  "will": {ipa: "/wɪl/", pos: "v.aux.", cn: "将要", ex: ["AI will reshape the economy.", "I will call you tomorrow."]},
  "would": {ipa: "/wʊd/", pos: "v.aux.", cn: "会；将要（过去式/虚拟）", ex: ["What would you do?", "I would like some tea."]},
  "should": {ipa: "/ʃʊd/", pos: "v.aux.", cn: "应该", ex: ["Should we take the bus?", "You should study hard."]},
  "could": {ipa: "/kʊd/", pos: "v.aux.", cn: "能够（过去式/虚拟）", ex: ["Could you help me?", "I could not believe it."]},
  "of": {ipa: "/əv/", pos: "prep.", cn: "……的", ex: ["The state of the art.", "One of my friends."]},
  "on": {ipa: "/ɒn/", pos: "prep.", cn: "在……之上；关于", ex: ["The cat is on the sofa.", "The report on the project."]},
  "in": {ipa: "/ɪn/", pos: "prep.", cn: "在……里面", ex: ["We live in a big city.", "In the morning."]},
  "at": {ipa: "/æt/", pos: "prep.", cn: "在；于", ex: ["The train arrives at nine.", "I am at home."]},
  "to": {ipa: "/tuː/", pos: "prep.", cn: "到；向", ex: ["Welcome to China.", "Go to school."]},
  "for": {ipa: "/fɔːr/", pos: "prep.", cn: "为了；给", ex: ["This is for you.", "Wait for the bus."]},
  "with": {ipa: "/wɪð/", pos: "prep.", cn: "和；带着", ex: ["Come with me.", "A girl with blue eyes."]},
  "from": {ipa: "/frɒm/", pos: "prep.", cn: "来自", ex: ["Where are you from?", "From morning till night."]},
  "by": {ipa: "/baɪ/", pos: "prep.", cn: "通过；在……旁边", ex: ["Travel by train.", "Stand by me."]},
  "as": {ipa: "/æz/", pos: "conj./prep.", cn: "作为；当……时", ex: ["As you know.", "He works as a doctor."]},
  "about": {ipa: "/əˈbaʊt/", pos: "prep./adv.", cn: "关于；大约", ex: ["Talk about it.", "About ten minutes."]},
  "into": {ipa: "/ˈɪntuː/", pos: "prep.", cn: "进入", ex: ["Go into the room.", "Change into something else."]},
  "out": {ipa: "/aʊt/", pos: "adv.", cn: "在外", ex: ["Go out.", "It is raining outside."]},
  "up": {ipa: "/ʌp/", pos: "adv./prep.", cn: "向上", ex: ["Stand up.", "Up the hill."]},
  "down": {ipa: "/daʊn/", pos: "adv./prep.", cn: "向下", ex: ["Sit down.", "Walk down the street."]},
  "over": {ipa: "/ˈoʊvər/", pos: "prep./adv.", cn: "在……上方；超过", ex: ["Over the bridge.", "Over five years."]},
  "after": {ipa: "/ˈæftər/", pos: "prep./conj.", cn: "在……之后", ex: ["After school.", "After you finish."]},
  "before": {ipa: "/bɪˈfɔːr/", pos: "prep./conj.", cn: "在……之前", ex: ["Before bed.", "Before the deadline."]},
  "through": {ipa: "/θruː/", pos: "prep.", cn: "穿过；通过", ex: ["Walk through the park.", "Through hard work."]},
  "between": {ipa: "/bɪˈtwiːn/", pos: "prep.", cn: "在……之间", ex: ["Between two trees.", "Between you and me."]},
  "during": {ipa: "/ˈdjʊərɪŋ/", pos: "prep.", cn: "在……期间", ex: ["During the holiday.", "During the meeting."]},
  "without": {ipa: "/wɪˈðaʊt/", pos: "prep.", cn: "没有", ex: ["Without help.", "Without doubts."]},
  "within": {ipa: "/wɪˈðɪn/", pos: "prep.", cn: "在……之内", ex: ["Within walking distance.", "Within the next decade."]},
  "if": {ipa: "/ɪf/", pos: "conj.", cn: "如果", ex: ["If you like it.", "If it rains tomorrow."]},
  "so": {ipa: "/soʊ/", pos: "adv./conj.", cn: "所以；如此", ex: ["So far.", "I am so happy."]},
  "because": {ipa: "/bɪˈkɒz/", pos: "conj.", cn: "因为", ex: ["Because of you.", "Just because."]},
  "while": {ipa: "/waɪl/", pos: "conj./n.", cn: "当……时；一会儿", ex: ["While I was reading.", "For a while."]},
  "until": {ipa: "/ʌnˈtɪl/", pos: "conj./prep.", cn: "直到", ex: ["Until tomorrow.", "Until you finish."]},
  "since": {ipa: "/sɪns/", pos: "conj./prep.", cn: "自……以来", ex: ["Since January.", "Since I met you."]},
  "more": {ipa: "/mɔːr/", pos: "adv./adj.", cn: "更多", ex: ["More and more.", "More than enough."]},
  "most": {ipa: "/moʊst/", pos: "adv./adj.", cn: "最；大多数", ex: ["Most people.", "The most important."]},
  "all": {ipa: "/ɔːl/", pos: "det./adv./pron.", cn: "全部", ex: ["All day long.", "All of us."]},
  "any": {ipa: "/ˈɛni/", pos: "det./pron.", cn: "任何", ex: ["Any questions?", "If there is any."]},
  "both": {ipa: "/boʊθ/", pos: "det./pron.", cn: "两者都", ex: ["Both of them.", "They both like it."]},
  "each": {ipa: "/iːtʃ/", pos: "det./pron.", cn: "每个", ex: ["Each person.", "Each of us."]},
  "only": {ipa: "/ˈoʊnli/", pos: "adv./adj.", cn: "只有；唯一的", ex: ["Only you.", "The only one."]},
  "other": {ipa: "/ˈʌðər/", pos: "adj./pron.", cn: "其他的", ex: ["Other people.", "Each other."]},
  "such": {ipa: "/sʌtʃ/", pos: "adj./det.", cn: "如此的；这样的", ex: ["Such a nice day.", "Such as."]},
  "than": {ipa: "/ðæn/", pos: "conj.", cn: "比", ex: ["Better than nothing.", "More than ten."]},
  "then": {ipa: "/ðɛn/", pos: "adv.", cn: "然后", ex: ["And then what?", "Then we went home."]},
  "there": {ipa: "/ðɛr/", pos: "adv.", cn: "那里", ex: ["Over there.", "There is a book."]},
  "here": {ipa: "/hɪr/", pos: "adv.", cn: "这里", ex: ["Come here.", "Here is your coffee."]},
  "yes": {ipa: "/jɛs/", pos: "adv.", cn: "是的", ex: ["Yes, please.", "She said yes."]},
  "no": {ipa: "/noʊ/", pos: "adv./adj.", cn: "不；没有", ex: ["No problem.", "I have no time."]},
  "never": {ipa: "/ˈnɛvər/", pos: "adv.", cn: "从不", ex: ["Never give up.", "I have never been there."]},
  "ever": {ipa: "/ˈɛvər/", pos: "adv.", cn: "曾经", ex: ["Have you ever been there?", "Best ever."]},
  "always": {ipa: "/ˈɔːlweɪz/", pos: "adv.", cn: "总是", ex: ["Always double check.", "I always drink tea."]},
  "working": {ipa: "/ˈwɜːrkɪŋ/", pos: "v.pres-p./adj.", cn: "工作中的；正在工作", ex: ["I have been working all day.", "A working environment."]},
  "worked": {ipa: "/wɜːrkt/", pos: "v.past/v.past-p.", cn: "工作（过去式/分词）", ex: ["I worked yesterday.", "Everything worked out."]},
  "studying": {ipa: "/ˈstʌdiɪŋ/", pos: "v.pres-p.", cn: "正在学习", ex: ["I have been studying English.", "Studying in groups."]},
  "studied": {ipa: "/ˈstʌdid/", pos: "v.past/v.past-p.", cn: "学习（过去式/分词）", ex: ["She studied music.", "A well-studied subject."]},
  "learning": {ipa: "/ˈlɜːrnɪŋ/", pos: "v.pres-p.", cn: "学习中", ex: ["Learning a new language.", "Keep on learning."]},
  "learned": {ipa: "/lɜːrnd/", pos: "v.past/v.past-p.", cn: "学习（过去式/分词）", ex: ["We learned from mistakes.", "A learned person."]},
  "playing": {ipa: "/ˈpleɪɪŋ/", pos: "v.pres-p.", cn: "正在玩/演奏", ex: ["They are playing in the garden.", "She is playing the piano."]},
  "played": {ipa: "/pleɪd/", pos: "v.past/v.past-p.", cn: "玩/演奏（过去式/分词）", ex: ["He played very well.", "The game was played yesterday."]},
  "sleeping": {ipa: "/ˈsliːpɪŋ/", pos: "v.pres-p.", cn: "正在睡觉", ex: ["The cat is sleeping.", "A sleeping baby."]},
  "reading": {ipa: "/ˈriːdɪŋ/", pos: "v.pres-p./n.", cn: "正在阅读；阅读", ex: ["I enjoy reading.", "She is reading a book."]},
  "writing": {ipa: "/ˈraɪtɪŋ/", pos: "v.pres-p./n.", cn: "正在写；写作", ex: ["Writing a report.", "His writing is clear."]},
  "taking": {ipa: "/ˈteɪkɪŋ/", pos: "v.pres-p.", cn: "正在拿/采取", ex: ["Taking a deep breath.", "Are you taking the bus?"]},
  "taken": {ipa: "/ˈteɪkən/", pos: "v.past-p.", cn: "拿（过去分词）", ex: ["Is this seat taken?", "The trip ever taken."]},
  "giving": {ipa: "/ˈɡɪvɪŋ/", pos: "v.pres-p.", cn: "正在给", ex: ["Giving a presentation.", "Thanks for giving it."]},
  "given": {ipa: "/ˈɡɪvən/", pos: "v.past-p.", cn: "给（过去分词）", ex: ["A given name.", "Everything was given."]},
  "speaking": {ipa: "/ˈspiːkɪŋ/", pos: "v.pres-p.", cn: "正在说话/讲", ex: ["Speaking of which.", "Are you speaking English?"]},
  "spoken": {ipa: "/ˈspoʊkən/", pos: "v.past-p.", cn: "说（过去分词）", ex: ["Spoken English.","Nothing was spoken."]},
  "thinking": {ipa: "/ˈθɪŋkɪŋ/", pos: "v.pres-p./n.", cn: "正在思考；化作", ex: ["Thinking about you.", "Creative thinking."]},
  "thought": {ipa: "/θɔːt/", pos: "v.past/n.", cn: "想（过去式）；思想", ex: ["I thought you knew.", "A deep thought."]},
  "say": {ipa: "/seɪ/", pos: "v.", cn: "说", ex: ["How do you say this?", "What did you say?"]},
  "said": {ipa: "/sɛd/", pos: "v.past/v.past-p.", cn: "说（过去式/分词）", ex: ["She said yes.", "It is said that..."]},
  "tell": {ipa: "/tɛl/", pos: "v.", cn: "告诉", ex: ["Tell me the story.", "Can you tell me where?"]},
  "told": {ipa: "/toʊld/", pos: "v.past/v.past-p.", cn: "告诉（过去式/分词）", ex: ["I told you so.", "She was told to wait."]},
  "start": {ipa: "/stɑːrt/", pos: "v./n.", cn: "开始", ex: ["Start learning.", "A new start."]},
  "started": {ipa: "/ˈstɑːrtɪd/", pos: "v.past/v.past-p.", cn: "开始（过去式/分词）", ex: ["It started to rain.", "The meeting started at nine."]},
  "finish": {ipa: "/ˈfɪnɪʃ/", pos: "v./n.", cn: "结束；完成", ex: ["Finish your work.", "A photo finish."]},
  "finished": {ipa: "/ˈfɪnɪʃt/", pos: "v.past/v.past-p.", cn: "结束（过去式/分词）", ex: ["Have you finished?", "A finished product."]},
  "going": {ipa: "/ˈɡoɪŋ/", pos: "v.pres-p.", cn: "正在去", ex: ["I am going home.", "What is going on?"]},
  "gone": {ipa: "/ɡɒn/", pos: "v.past-p.", cn: "去（过去分词）；离开的", ex: ["She has gone to Paris.", "The time is gone."]},
  "went": {ipa: "/wɛnt/", pos: "v.past", cn: "去（过去式）", ex: ["We went to the park.", "Everything went well."]},
  "coming": {ipa: "/ˈkʌmɪŋ/", pos: "v.pres-p./adj.", cn: "正在来；即将到来的", ex: ["Summer is coming.", "The coming week."]},
  "making": {ipa: "/ˈmeɪkɪŋ/", pos: "v.pres-p.", cn: "正在制作", ex: ["Making a difference.", "Making a decision."]},
  "made": {ipa: "/meɪd/", pos: "v.past/v.past-p.", cn: "制作（过去式/分词）", ex: ["I made a mistake.", "Made in China."]},
  "looking": {ipa: "/ˈlʊkɪŋ/", pos: "v.pres-p.", cn: "正在看", ex: ["Looking for the library.", "Looking forward to it."]},
  "looked": {ipa: "/lʊkt/", pos: "v.past/v.past-p.", cn: "看（过去式/分词）", ex: ["She looked at me.", "Everything looked fine."]},
  "raining": {ipa: "/ˈreɪnɪŋ/", pos: "v.pres-p.", cn: "正在下雨", ex: ["It is raining outside.", "Raining cats and dogs."]},
  "felt": {ipa: "/fɛlt/", pos: "v.past/v.past-p.", cn: "感觉（过去式/分词）", ex: ["I felt happy.", "She felt a bit tired."]},
  "become": {ipa: "/bɪˈkʌm/", pos: "v.", cn: "成为", ex: ["Become a doctor.", "Technology has become..."]},
  "became": {ipa: "/bɪˈkeɪm/", pos: "v.past", cn: "成为（过去式）", ex: ["He became famous.", "It became clear."]},
  "becoming": {ipa: "/bɪˈkʌmɪŋ/", pos: "v.pres-p.", cn: "正在成为", ex: ["Public transportation is becoming...", "Becoming a leader."]},
  "apply": {ipa: "/əˈplaɪ/", pos: "v.", cn: "申请；应用", ex: ["Apply for a job.", "Apply the rules."]},
  "applying": {ipa: "/əˈplaɪɪŋ/", pos: "v.pres-p.", cn: "正在申请/应用", ex: ["Applying for that position.", "Applying new methods."]},
  "applied": {ipa: "/əˈplaɪd/", pos: "v.past/v.past-p.", cn: "申请/应用（过去式/分词）", ex: ["She applied for a loan.", "Applied science."]},
  "decide": {ipa: "/dɪˈsaɪd/", pos: "v.", cn: "决定", ex: ["Decide to change.", "You must decide now."]},
  "decided": {ipa: "/dɪˈsaɪdɪd/", pos: "v.past/v.past-p.", cn: "决定（过去式/分词）", ex: ["She decided to pursue...", "A decided advantage."]},
  "inspired": {ipa: "/ɪnˈspaɪərd/", pos: "v.past/adj.", cn: "激励（过去式）；受启发的", ex: ["What inspired you?", "An inspired performance."]},
  "inspiring": {ipa: "/ɪnˈspaɪərɪŋ/", pos: "adj.", cn: "鼓舞人心的", ex: ["An inspiring story.", "How inspiring it is!"]},
  "experienced": {ipa: "/ɪkˈspɪəriənst/", pos: "v.past/adj.", cn: "体验（过去式）；有经验的", ex: ["We experienced growth.", "An experienced teacher."]},
  "experiencing": {ipa: "/ɪkˈspɪəriənsɪŋ/", pos: "v.pres-p.", cn: "正在经历", ex: ["Experiencing steady growth.", "Experiencing difficulties."]},
  "considered": {ipa: "/kənˈsɪdərd/", pos: "v.past/v.past-p.", cn: "考虑（过去式/分词）", ex: ["Have you considered...?", "A well-considered plan."]},
  "considering": {ipa: "/kənˈsɪdərɪŋ/", pos: "v.pres-p./prep.", cn: "正在考虑；考虑到", ex: ["Considering all options.", "Considering the price."]},
  "realized": {ipa: "/ˈrɪəlaɪzd/", pos: "v.past/v.past-p.", cn: "意识到（过去式/分词）", ex: ["He realized that...", "A dream realized."]},
  "realizing": {ipa: "/ˈrɪəlaɪzɪŋ/", pos: "v.pres-p.", cn: "正在意识到", ex: ["Realizing the truth.", "Realizing my potential."]},
  "maintain": {ipa: "/meɪnˈteɪn/", pos: "v.", cn: "维持；保持", ex: ["Maintain a positive attitude.", "Maintain the building."]},
  "maintaining": {ipa: "/meɪnˈteɪnɪŋ/", pos: "v.pres-p.", cn: "正在维持", ex: ["Maintaining a good pace.", "Maintaining consistency."]},
  "elaborate": {ipa: "/ɪˈlæbəreɪt/", pos: "v./adj.", cn: "详细说明；详尽的", ex: ["Could you elaborate?", "An elaborate plan."]},
  "scrutinize": {ipa: "/ˈskruːtɪnaɪz/", pos: "v.", cn: "仔细检查", ex: ["Scrutinize the data.", "The results were scrutinized."]},
  "mitigate": {ipa: "/ˈmɪtɪɡeɪt/", pos: "v.", cn: "减轻；缓解", ex: ["Mitigate the effects.", "Mitigate the risks."]},
  "exacerbated": {ipa: "/ɪɡˈzæsərbeɪtɪd/", pos: "v.past/v.past-p.", cn: "加剧（过去式/分词）", ex: ["Globalization has exacerbated...", "The problem was exacerbated."]},
  "address": {ipa: "/əˈdrɛs/", pos: "v./n.", cn: "处理设备；地址", ex: ["Address the challenge.", "What is your address?"]},
  "addressing": {ipa: "/əˈdrɛsɪŋ/", pos: "v.pres-p.", cn: "正在处理", ex: ["Addressing complex challenges.", "Addressing the audience."]},
  "transform": {ipa: "/trænsˈfɔːrm/", pos: "v.", cn: "转变；转换", ex: ["Transform the way we live.", "Digital transform."]},
  "transformed": {ipa: "/trænsˈfɔːrmd/", pos: "v.past/v.past-p.", cn: "转变（过去式/分词）", ex: ["Technology has transformed...", "A transformed society."]},
  "reshape": {ipa: "/riːˈʃeɪp/", pos: "v.", cn: "重塑", ex: ["Reshape the economy.", "Reshape the future."]},
  "revealed": {ipa: "/rɪˈviːld/", pos: "v.past/v.past-p.", cn: "揭示（过去式/分词）", ex: ["Research has revealed...", "The secret was revealed."]},
  "balances": {ipa: "/ˈbælənsɪz/", pos: "v.", cn: "平衡（第三人称单数）", ex: ["She balances work and life.", "The budget balances."]},
  "balancing": {ipa: "/ˈbælənsɪŋ/", pos: "v.pres-p.", cn: "正在平衡", ex: ["Balancing work and life.", "A balancing act."]},
  "prioritize": {ipa: "/praɪˈɒrɪtaɪz/", pos: "v.", cn: "优先考虑", ex: ["Prioritize tasks.", "Governments should prioritize..."]},
  "prioritizing": {ipa: "/praɪˈɒrɪtaɪzɪŋ/", pos: "v.pres-p.", cn: "正在优先考虑", ex: ["Prioritizing safety.", "Prioritizing environmental care."]},
  "foster": {ipa: "/ˈfɒstər/", pos: "v.", cn: "培养；促进", ex: ["Foster critical thinking.", "Foster a good relationship."]},
  "perpetuating": {ipa: "/pərˈpɛtʃueɪtɪŋ/", pos: "v.pres-p.", cn: "使持续；使永恒", ex: ["Perpetuating systemic discrimination.", "Perpetuating the cycle."]},
  "integrating": {ipa: "/ˈɪntɪɡreɪtɪŋ/", pos: "v.pres-p.", cn: "整合中", ex: ["Integrating synthetic assets.", "Integrating new members."]},
  "integrated": {ipa: "/ˈɪntɪɡreɪtɪd/", pos: "v.past/adj.", cn: "整合（过去式）；综合的", ex: ["An integrated circuit.", "They integrated the systems."]},
  "cultivating": {ipa: "/ˈkʌltɪveɪtɪŋ/", pos: "v.pres-p.", cn: "耕作；培养", ex: ["Cultivating a framework.", "Cultivating land."]},
  "bridging": {ipa: "/ˈbrɪdʒɪŋ/", pos: "v.pres-p.", cn: "架桥；连接", ex: ["Bridging the gap.", "Bridging societies."]},
  "underestimated": {ipa: "/ˌʌndərˈɛstɪmeɪtɪd/", pos: "v.past/v.past-p.", cn: "低估（过去式/分词）", ex: ["We have underestimated the budget.", "Never underestimated the enemy."]},
  "rescheduled": {ipa: "/riːˈskɛdʒuːld/", pos: "v.past/v.past-p.", cn: "重新安排（过去式/分词）", ex: ["The meeting was rescheduled.", "I rescheduled my appointment."]},
  "thoroughly": {ipa: "/ˈθʌrəli/", pos: "adv.", cn: "彻底地", ex: ["Thoroughly review the proposal.", "Clean the room thoroughly."]},
  "fundamentally": {ipa: "/ˌfʌndəˈmɛntəli/", pos: "adv.", cn: "根本地", ex: ["They are fundamentally different.", "Fundamentally, I argue..."]},
  "precisely": {ipa: "/prɪˈsaɪsli/", pos: "adv.", cn: "精确地；恰恰", ex: ["Precisely what I meant.", "Measure precisely."]},
  "absolutely": {ipa: "/ˌæbsəˈluːtli/", pos: "adv.", cn: "绝对地", ex: ["Absolutely undeniable.", "You are absolutely right."]},
  "inevitably": {ipa: "/ɪnˈɛvɪtəbli/", pos: "adv.", cn: "不可避免地", ex: ["Inevitably leads to friction.", "It will inevitably happen."]},
  "significantly": {ipa: "/sɪɡˈnɪfɪkəntli/", pos: "adv.", cn: "显著地", ex: ["Significantly reduces risk.", "Increase significantly."]},
  "increasingly": {ipa: "/ɪnˈkriːsɪŋli/", pos: "adv.", cn: "日益地", ex: ["Increasingly indispensable.", "Increasingly difficult."]},
  "empirically": {ipa: "/ɪmˈpɪrɪkəli/", pos: "adv.", cn: "凭经验地", ex: ["Empirically validated.", "Tested empirically."]},
  "profoundly": {ipa: "/prəˈfaʊndli/", pos: "adv.", cn: "深刻地", ex: ["Profoundly altered society.", "I am profoundly moved."]},
  "actually": {ipa: "/ˈæktʃuəli/", pos: "adv.", cn: "实际上", ex: ["I was actually planning...", "What actually happened?"]},
  "perfectly": {ipa: "/ˈpɜːrfɪktli/", pos: "adv.", cn: "完美地", ex: ["Perfectly walkable.", "It works perfectly."]},
  "quickly": {ipa: "/ˈkwɪkli/", pos: "adv.", cn: "快地", ex: ["Come here quickly.", "Time passes quickly."]},
  "regularly": {ipa: "/ˈrɛɡjələrli/", pos: "adv.", cn: "定期地", ex: ["Back up files regularly.", "Exercise regularly."]},
  "beautifully": {ipa: "/ˈbjuːtɪfəli/", pos: "adv.", cn: "美丽地", ex: ["Played beautifully.", "She sings beautifully."]},
  "well": {ipa: "/wɛl/", pos: "adv./adj.", cn: "好地；好的", ex: ["Played very well.", "I am well."]},
  "ever": {ipa: "/ˈɛvər/", pos: "adv.", cn: "曾经", ex: ["Have you ever been...?", "Best ever taken."]},
  "never": {ipa: "/ˈnɛvər/", pos: "adv.", cn: "从未", ex: ["Never give up.", "I have never seen it."]},
  "always": {ipa: "/ˈɔːlweɪz/", pos: "adv.", cn: "总是", ex: ["Always double check.", "I always drink coffee."]},
  "often": {ipa: "/ˈɒfən/", pos: "adv.", cn: "经常", ex: ["How often do you exercise?", "I often go there."]},
  "usually": {ipa: "/ˈjuːʒuəli/", pos: "adv.", cn: "通常", ex: ["Usually listen to music.", "I usually wake up at six."]},
  "about": {ipa: "/əˈbaʊt/", pos: "prep./adv.", cn: "关于；大约", ex: ["About ten minutes.", "Think about it."]},
  "just": {ipa: "/dʒʌst/", pos: "adv./adj.", cn: "仅仅；刚才；公正的", ex: ["Just a moment.", "I just arrived."]}
};
