// ==================== SENTENCE DATABASE ====================
const SENTENCES = [
  // ===== INTERROGATIVE - ELEMENTARY =====
  {id:1,text:"What is your name?",type:"interrogative",sub:"general",level:"elementary",cn:"你叫什么名字？"},
  {id:2,text:"How are you today?",type:"interrogative",sub:"general",level:"elementary",cn:"你今天好吗？"},
  {id:3,text:"Where do you live?",type:"interrogative",sub:"special",level:"elementary",cn:"你住在哪里？"},
  {id:4,text:"Do you like coffee?",type:"interrogative",sub:"general",level:"elementary",cn:"你喜欢咖啡吗？"},
  {id:5,text:"What time is it?",type:"interrogative",sub:"special",level:"elementary",cn:"现在几点了？"},
  {id:6,text:"Can you help me?",type:"interrogative",sub:"general",level:"elementary",cn:"你能帮我吗？"},
  {id:7,text:"Is this your book?",type:"interrogative",sub:"general",level:"elementary",cn:"这是你的书吗？"},
  {id:8,text:"Where is the bathroom?",type:"interrogative",sub:"special",level:"elementary",cn:"洗手间在哪里？"},
  {id:9,text:"How much does it cost?",type:"interrogative",sub:"special",level:"elementary",cn:"这个多少钱？"},
  {id:10,text:"Do you have any brothers or sisters?",type:"interrogative",sub:"general",level:"elementary",cn:"你有兄弟姐妹吗？"},
  {id:11,text:"What color do you like?",type:"interrogative",sub:"special",level:"elementary",cn:"你喜欢什么颜色？"},
  {id:12,text:"Are you hungry?",type:"interrogative",sub:"general",level:"elementary",cn:"你饿了吗？"},
  {id:13,text:"When is your birthday?",type:"interrogative",sub:"special",level:"elementary",cn:"你的生日是什么时候？"},
  {id:14,text:"Do you speak English?",type:"interrogative",sub:"general",level:"elementary",cn:"你会说英语吗？"},
  {id:15,text:"Who is your teacher?",type:"interrogative",sub:"special",level:"elementary",cn:"你的老师是谁？"},
  {id:16,text:"Can I have some water?",type:"interrogative",sub:"general",level:"elementary",cn:"我能喝点水吗？"},
  {id:17,text:"What is your favorite food?",type:"interrogative",sub:"special",level:"elementary",cn:"你最喜欢的食物是什么？"},
  {id:18,text:"Is it raining outside?",type:"interrogative",sub:"general",level:"elementary",cn:"外面在下雨吗？"},
  {id:19,text:"How old are you?",type:"interrogative",sub:"special",level:"elementary",cn:"你多大了？"},
  {id:20,text:"Would you like some tea?",type:"interrogative",sub:"general",level:"elementary",cn:"你想喝茶吗？"},
  {id:21,text:"Where are you from?",type:"interrogative",sub:"special",level:"elementary",cn:"你来自哪里？"},
  {id:22,text:"Is this seat taken?",type:"interrogative",sub:"general",level:"elementary",cn:"这个座位有人吗？"},
  {id:23,text:"What day is today?",type:"interrogative",sub:"special",level:"elementary",cn:"今天星期几？"},
  {id:24,text:"Do you want to play?",type:"interrogative",sub:"general",level:"elementary",cn:"你想玩吗？"},
  {id:25,text:"How do you say this in English?",type:"interrogative",sub:"special",level:"elementary",cn:"这个用英语怎么说？"},

  // ===== INTERROGATIVE - INTERMEDIATE =====
  {id:26,text:"Have you ever been to Japan?",type:"interrogative",sub:"general",level:"intermediate",cn:"你去过日本吗？"},
  {id:27,text:"What would you do if you won the lottery?",type:"interrogative",sub:"special",level:"intermediate",cn:"如果你中了彩票你会做什么？"},
  {id:28,text:"Could you tell me where the nearest station is?",type:"interrogative",sub:"general",level:"intermediate",cn:"你能告诉我最近的车站在哪吗？"},
  {id:29,text:"How long have you been studying English?",type:"interrogative",sub:"special",level:"intermediate",cn:"你学英语学了多久了？"},
  {id:30,text:"Would you mind opening the window?",type:"interrogative",sub:"general",level:"intermediate",cn:"你介意开窗吗？"},
  {id:31,text:"Why did you decide to change your career?",type:"interrogative",sub:"special",level:"intermediate",cn:"你为什么决定换职业？"},
  {id:32,text:"Have you finished reading that book yet?",type:"interrogative",sub:"general",level:"intermediate",cn:"你读完那本书了吗？"},
  {id:33,text:"What kind of music do you usually listen to?",type:"interrogative",sub:"special",level:"intermediate",cn:"你通常听什么类型的音乐？"},
  {id:34,text:"Isn't it a beautiful day for a walk?",type:"interrogative",sub:"tag",level:"intermediate",cn:"今天天气很适合散步，不是吗？"},
  {id:35,text:"Do you prefer working from home or the office?",type:"interrogative",sub:"choice",level:"intermediate",cn:"你喜欢在家还是在办公室工作？"},
  {id:36,text:"What are your plans for the weekend?",type:"interrogative",sub:"special",level:"intermediate",cn:"你周末有什么计划？"},
  {id:37,text:"Should we take the bus or walk there?",type:"interrogative",sub:"choice",level:"intermediate",cn:"我们应该坐公交还是步行去？"},
  {id:38,text:"How often do you exercise?",type:"interrogative",sub:"special",level:"intermediate",cn:"你多久锻炼一次？"},
  {id:39,text:"You have been to London before, haven't you?",type:"interrogative",sub:"tag",level:"intermediate",cn:"你以前去过伦敦，对吧？"},
  {id:40,text:"What inspired you to start learning a new language?",type:"interrogative",sub:"special",level:"intermediate",cn:"是什么激励你开始学一门新语言的？"},
  {id:41,text:"Could you recommend a good restaurant nearby?",type:"interrogative",sub:"general",level:"intermediate",cn:"你能推荐附近一家好餐厅吗？"},
  {id:42,text:"Do you think technology makes our lives easier?",type:"interrogative",sub:"general",level:"intermediate",cn:"你认为技术让我们的生活更容易了吗？"},
  {id:43,text:"Where did you grow up?",type:"interrogative",sub:"special",level:"intermediate",cn:"你在哪里长大的？"},
  {id:44,text:"Have you considered applying for that position?",type:"interrogative",sub:"general",level:"intermediate",cn:"你考虑过申请那个职位吗？"},
  {id:45,text:"What makes you happy?",type:"interrogative",sub:"special",level:"intermediate",cn:"什么让你开心？"},
  {id:46,text:"Would you rather travel by train or by plane?",type:"interrogative",sub:"choice",level:"intermediate",cn:"你更愿意坐火车还是飞机旅行？"},
  {id:47,text:"She passed the exam, didn't she?",type:"interrogative",sub:"tag",level:"intermediate",cn:"她通过考试了，不是吗？"},
  {id:48,text:"How do you usually spend your holidays?",type:"interrogative",sub:"special",level:"intermediate",cn:"你通常怎么度过假期？"},
  {id:49,text:"Can you explain this concept to me?",type:"interrogative",sub:"general",level:"intermediate",cn:"你能给我解释一下这个概念吗？"},
  {id:50,text:"What was the most memorable trip you have ever taken?",type:"interrogative",sub:"special",level:"intermediate",cn:"你最难忘的旅行是哪次？"},

  // ===== INTERROGATIVE - ADVANCED =====
  {id:51,text:"To what extent do you think artificial intelligence will reshape the global economy?",type:"interrogative",sub:"special",level:"advanced",cn:"你认为人工智能将在多大程度上重塑全球经济？"},
  {id:52,text:"Wouldn't it be more prudent to diversify the investment portfolio before the fiscal quarter ends?",type:"interrogative",sub:"tag",level:"advanced",cn:"在财季结束前分散投资组合不是更明智吗？"},
  {id:53,text:"How might sustainable urban planning mitigate the effects of climate change?",type:"interrogative",sub:"special",level:"advanced",cn:"可持续城市规划如何能减轻气候变化的影响？"},
  {id:54,text:"Should governments prioritize economic growth over environmental conservation?",type:"interrogative",sub:"choice",level:"advanced",cn:"政府是否应该将经济增长置于环境保护之上？"},
  {id:55,text:"What philosophical implications arise from advances in genetic engineering?",type:"interrogative",sub:"special",level:"advanced",cn:"基因工程的进步会带来哪些哲学层面的影响？"},
  {id:56,text:"Could you elaborate on how quantum computing differs from classical computation?",type:"interrogative",sub:"general",level:"advanced",cn:"你能详细说明量子计算与经典计算有何不同吗？"},
  {id:57,text:"Is it not the case that prolonged social isolation leads to cognitive deterioration?",type:"interrogative",sub:"tag",level:"advanced",cn:"长期社交隔离会导致认知退化，不是吗？"},
  {id:58,text:"To what degree has globalization exacerbated socioeconomic inequality?",type:"interrogative",sub:"special",level:"advanced",cn:"全球化在多大程度上加剧了社会经济不平等？"},
  {id:59,text:"How can educational institutions foster critical thinking in an era of misinformation?",type:"interrogative",sub:"special",level:"advanced",cn:"教育机构如何在错误信息时代培养批判性思维？"},
  {id:60,text:"Would it be feasible to implement universal basic income on a national scale?",type:"interrogative",sub:"general",level:"advanced",cn:"在全国范围内实施全民基本收入是否可行？"},
  {id:61,text:"What role does unconscious bias play in perpetuating systemic discrimination?",type:"interrogative",sub:"special",level:"advanced",cn:"无意识偏见在延续系统性歧视中扮演什么角色？"},
  {id:62,text:"Haven't recent neurological studies debunked the myth of left-brain right-brain dominance?",type:"interrogative",sub:"tag",level:"advanced",cn:"最近的神经学研究不是已经推翻了左右脑主导的迷信吗？"},
  {id:63,text:"How should multinational corporations balance profitability with corporate social responsibility?",type:"interrogative",sub:"special",level:"advanced",cn:"跨国公司应如何平衡盈利能力与企业社会责任？"},
  {id:64,text:"What are the ethical boundaries of surveillance technology in democratic societies?",type:"interrogative",sub:"special",level:"advanced",cn:"民主社会中监控技术的伦理边界在哪里？"},
  {id:65,text:"Should autonomous vehicles be programmed to prioritize passenger safety or pedestrian safety?",type:"interrogative",sub:"choice",level:"advanced",cn:"自动驾驶车辆应该优先考虑乘客安全还是行人安全？"},

  // ===== DECLARATIVE - ELEMENTARY =====
  {id:100,text:"I like to eat apples.",type:"declarative",sub:"declarative",level:"elementary",cn:"我喜欢吃苹果。"},
  {id:101,text:"The sun is very hot.",type:"declarative",sub:"declarative",level:"elementary",cn:"太阳很热。"},
  {id:102,text:"She is my best friend.",type:"declarative",sub:"declarative",level:"elementary",cn:"她是我最好的朋友。"},
  {id:103,text:"We go to school every day.",type:"declarative",sub:"declarative",level:"elementary",cn:"我们每天去上学。"},
  {id:104,text:"My dog is very cute.",type:"declarative",sub:"declarative",level:"elementary",cn:"我的狗很可爱。"},
  {id:105,text:"It is cold outside.",type:"declarative",sub:"declarative",level:"elementary",cn:"外面很冷。"},
  {id:106,text:"I have two brothers.",type:"declarative",sub:"declarative",level:"elementary",cn:"我有两个兄弟。"},
  {id:107,text:"The cat is sleeping on the sofa.",type:"declarative",sub:"declarative",level:"elementary",cn:"猫在沙发上睡觉。"},
  {id:108,text:"Today is Monday.",type:"declarative",sub:"declarative",level:"elementary",cn:"今天是星期一。"},
  {id:109,text:"I drink milk every morning.",type:"declarative",sub:"declarative",level:"elementary",cn:"我每天早上喝牛奶。"},
  {id:110,text:"She plays the piano very well.",type:"declarative",sub:"declarative",level:"elementary",cn:"她钢琴弹得很好。"},
  {id:111,text:"We live in a big city.",type:"declarative",sub:"declarative",level:"elementary",cn:"我们住在一个大城市。"},
  {id:112,text:"He goes to the park after school.",type:"declarative",sub:"declarative",level:"elementary",cn:"他放学后去公园。"},
  {id:113,text:"My mother cooks dinner every evening.",type:"declarative",sub:"declarative",level:"elementary",cn:"我妈妈每天晚上做晚饭。"},
  {id:114,text:"The flowers are beautiful.",type:"declarative",sub:"declarative",level:"elementary",cn:"花很漂亮。"},
  {id:115,text:"I read books before bed.",type:"declarative",sub:"declarative",level:"elementary",cn:"我睡前看书。"},
  {id:116,text:"They are playing in the garden.",type:"declarative",sub:"declarative",level:"elementary",cn:"他们在花园里玩。"},
  {id:117,text:"The water is very clean.",type:"declarative",sub:"declarative",level:"elementary",cn:"水很干净。"},
  {id:118,text:"I want to be a doctor.",type:"declarative",sub:"declarative",level:"elementary",cn:"我想成为一名医生。"},
  {id:119,text:"The movie was really funny.",type:"declarative",sub:"declarative",level:"elementary",cn:"那部电影真的很搞笑。"},
  {id:120,text:"Birds can fly in the sky.",type:"declarative",sub:"declarative",level:"elementary",cn:"鸟能在天空中飞翔。"},
  {id:121,text:"I like drawing pictures.",type:"declarative",sub:"declarative",level:"elementary",cn:"我喜欢画画。"},
  {id:122,text:"She wears a red dress.",type:"declarative",sub:"declarative",level:"elementary",cn:"她穿着一条红色的裙子。"},
  {id:123,text:"We had pizza for lunch.",type:"declarative",sub:"declarative",level:"elementary",cn:"我们午饭吃了披萨。"},
  {id:124,text:"The train arrives at nine o'clock.",type:"declarative",sub:"declarative",level:"elementary",cn:"火车九点到达。"},

  // ===== DECLARATIVE - INTERMEDIATE =====
  {id:125,text:"Learning a foreign language opens up a world of opportunities.",type:"declarative",sub:"declarative",level:"intermediate",cn:"学习外语会打开一个充满机会的世界。"},
  {id:126,text:"The company has been experiencing steady growth for the past five years.",type:"declarative",sub:"declarative",level:"intermediate",cn:"这家公司过去五年一直在稳步增长。"},
  {id:127,text:"Regular exercise significantly reduces the risk of heart disease.",type:"declarative",sub:"declarative",level:"intermediate",cn:"定期锻炼显著降低患心脏病的风险。"},
  {id:128,text:"Climate change is one of the most pressing challenges of our time.",type:"declarative",sub:"declarative",level:"intermediate",cn:"气候变化是我们时代最紧迫的挑战之一。"},
  {id:129,text:"The meeting has been rescheduled to next Thursday afternoon.",type:"declarative",sub:"declarative",level:"intermediate",cn:"会议已重新安排到下周四下午。"},
  {id:130,text:"She decided to pursue a career in environmental science.",type:"declarative",sub:"declarative",level:"intermediate",cn:"她决定从事环境科学事业。"},
  {id:131,text:"The new software update includes several important security patches.",type:"declarative",sub:"declarative",level:"intermediate",cn:"新的软件更新包含几个重要的安全补丁。"},
  {id:132,text:"They have been working on this project since January.",type:"declarative",sub:"declarative",level:"intermediate",cn:"他们从一月份开始就一直在做这个项目。"},
  {id:133,text:"Good communication skills are essential for professional success.",type:"declarative",sub:"declarative",level:"intermediate",cn:"良好的沟通技巧对职业成功至关重要。"},
  {id:134,text:"The research findings suggest a strong correlation between sleep and productivity.",type:"declarative",sub:"declarative",level:"intermediate",cn:"研究结果表明睡眠和生产力之间有很强的相关性。"},
  {id:135,text:"Public transportation is becoming more efficient in many major cities.",type:"declarative",sub:"declarative",level:"intermediate",cn:"许多大城市的公共交通正变得越来越高效。"},
  {id:136,text:"He realized that time management was the key to balancing work and life.",type:"declarative",sub:"declarative",level:"intermediate",cn:"他意识到时间管理是平衡工作和生活的关键。"},
  {id:137,text:"The restaurant on the corner serves the best pasta in town.",type:"declarative",sub:"declarative",level:"intermediate",cn:"街角的那家餐厅供应全城最好的意面。"},
  {id:138,text:"Technology continues to transform the way we interact with each other.",type:"declarative",sub:"declarative",level:"intermediate",cn:"技术继续改变着我们彼此互动的方式。"},
  {id:139,text:"Many students find it helpful to study in groups rather than alone.",type:"declarative",sub:"declarative",level:"intermediate",cn:"许多学生发现小组学习比独自学习更有帮助。"},

  // ===== DECLARATIVE - ADVANCED =====
  {id:140,text:"The proliferation of artificial intelligence has fundamentally altered the landscape of modern industry.",type:"declarative",sub:"declarative",level:"advanced",cn:"人工智能的普及从根本上改变了现代工业的格局。"},
  {id:141,text:"Neuroplasticity demonstrates that the human brain is far more adaptable than previously believed.",type:"declarative",sub:"declarative",level:"advanced",cn:"神经可塑性表明人脑比以前认为的更具适应性。"},
  {id:142,text:"The socioeconomic ramifications of the pandemic will reverberate for decades to come.",type:"declarative",sub:"declarative",level:"advanced",cn:"这次大流行的社会经济后果将在未来几十年内持续影响。"},
  {id:143,text:"Interdisciplinary collaboration has become increasingly indispensable in addressing complex global challenges.",type:"declarative",sub:"declarative",level:"advanced",cn:"跨学科合作在应对复杂的全球挑战中变得越来越不可或缺。"},
  {id:144,text:"The erosion of biodiversity poses an existential threat to the integrity of global ecosystems.",type:"declarative",sub:"declarative",level:"advanced",cn:"生物多样性的丧失对全球生态系统的完整性构成了生存威胁。"},
  {id:145,text:"Contemporary philosophical discourse increasingly grapples with the ethical implications of biotechnology.",type:"declarative",sub:"declarative",level:"advanced",cn:"当代哲学论述日益关注生物技术的伦理影响。"},
  {id:146,text:"Cognitive behavioral therapy has emerged as one of the most empirically validated psychotherapeutic approaches.",type:"declarative",sub:"declarative",level:"advanced",cn:"认知行为疗法已成为最具实证验证的心理治疗方法之一。"},
  {id:147,text:"The geopolitical tensions in the region have intensified due to competing territorial claims.",type:"declarative",sub:"declarative",level:"advanced",cn:"该地区因领土争端竞争加剧，地缘政治紧张局势加剧。"},
  {id:148,text:"Sustainable development requires a paradigm shift in how societies conceptualize economic progress.",type:"declarative",sub:"declarative",level:"advanced",cn:"可持续发展需要社会在如何看待经济增长方面进行范式转变。"},
  {id:149,text:"The democratization of information through digital platforms has both empowered and polarized public discourse.",type:"declarative",sub:"declarative",level:"advanced",cn:"通过数字平台实现信息民主化，既赋予了公众力量，也使公共话语两极化。"},
  {id:150,text:"Epigenetic research has revealed that environmental factors can influence gene expression across generations.",type:"declarative",sub:"declarative",level:"advanced",cn:"表观遗传学研究揭示了环境因素可以跨代影响基因表达。"},
  {id:151,text:"The implementation of blockchain technology promises to revolutionize supply chain transparency.",type:"declarative",sub:"declarative",level:"advanced",cn:"区块链技术的实施有望彻底改变供应链的透明度。"},

  // ===== IMPERATIVE - ELEMENTARY =====
  {id:200,text:"Please open the door.",type:"declarative",sub:"imperative",level:"elementary",cn:"请开门。"},
  {id:201,text:"Sit down, please.",type:"declarative",sub:"imperative",level:"elementary",cn:"请坐。"},
  {id:202,text:"Close the window.",type:"declarative",sub:"imperative",level:"elementary",cn:"关上窗户。"},
  {id:203,text:"Listen to me carefully.",type:"declarative",sub:"imperative",level:"elementary",cn:"仔细听我说。"},
  {id:204,text:"Turn off the light.",type:"declarative",sub:"imperative",level:"elementary",cn:"关灯。"},
  {id:205,text:"Write your name here.",type:"declarative",sub:"imperative",level:"elementary",cn:"在这里写上你的名字。"},
  {id:206,text:"Come here quickly.",type:"declarative",sub:"imperative",level:"elementary",cn:"快过来。"},
  {id:207,text:"Be quiet in the library.",type:"declarative",sub:"imperative",level:"elementary",cn:"在图书馆里要安静。"},
  {id:208,text:"Wash your hands before eating.",type:"declarative",sub:"imperative",level:"elementary",cn:"吃饭前洗手。"},
  {id:209,text:"Don't run in the hallway.",type:"declarative",sub:"imperative",level:"elementary",cn:"不要在走廊里跑。"},
  {id:210,text:"Give me the book.",type:"declarative",sub:"imperative",level:"elementary",cn:"把书给我。"},
  {id:211,text:"Stand up straight.",type:"declarative",sub:"imperative",level:"elementary",cn:"站直了。"},
  {id:212,text:"Clean your room.",type:"declarative",sub:"imperative",level:"elementary",cn:"打扫你的房间。"},

  // ===== IMPERATIVE - INTERMEDIATE =====
  {id:213,text:"Make sure you submit the report before the deadline.",type:"declarative",sub:"imperative",level:"intermediate",cn:"确保你在截止日期前提交报告。"},
  {id:214,text:"Always double-check your work before handing it in.",type:"declarative",sub:"imperative",level:"intermediate",cn:"交作业前务必仔细检查。"},
  {id:215,text:"Try to maintain a positive attitude even during challenging times.",type:"declarative",sub:"imperative",level:"intermediate",cn:"即使在困难时期也要保持积极态度。"},
  {id:216,text:"Consider all the options before making a final decision.",type:"declarative",sub:"imperative",level:"intermediate",cn:"在做最终决定前考虑所有选项。"},
  {id:217,text:"Take a deep breath and relax before the presentation.",type:"declarative",sub:"imperative",level:"intermediate",cn:"演讲前深呼吸放松一下。"},
  {id:218,text:"Remember to back up your files regularly.",type:"declarative",sub:"imperative",level:"intermediate",cn:"记得定期备份你的文件。"},

  // ===== IMPERATIVE - ADVANCED =====
  {id:219,text:"Endeavor to cultivate intellectual humility in all your academic pursuits.",type:"declarative",sub:"imperative",level:"advanced",cn:"在所有学术追求中努力培养知识上的谦逊。"},
  {id:220,text:"Scrutinize the methodology before drawing any conclusions from the data.",type:"declarative",sub:"imperative",level:"advanced",cn:"在从数据中得出结论之前，仔细审查方法论。"},
  {id:221,text:"Refrain from making premature judgments without thoroughly evaluating the evidence.",type:"declarative",sub:"imperative",level:"advanced",cn:"在没有彻底评估证据之前不要过早下结论。"},

  // ===== EXCLAMATORY - ELEMENTARY =====
  {id:300,text:"What a beautiful day!",type:"declarative",sub:"exclamatory",level:"elementary",cn:"多么美好的一天！"},
  {id:301,text:"How amazing this place is!",type:"declarative",sub:"exclamatory",level:"elementary",cn:"这个地方多么令人惊叹！"},
  {id:302,text:"What a surprise!",type:"declarative",sub:"exclamatory",level:"elementary",cn:"真是个惊喜！"},
  {id:303,text:"How wonderful!",type:"declarative",sub:"exclamatory",level:"elementary",cn:"太棒了！"},
  {id:304,text:"That was so much fun!",type:"declarative",sub:"exclamatory",level:"elementary",cn:"那太有趣了！"},
  {id:305,text:"What a cute puppy!",type:"declarative",sub:"exclamatory",level:"elementary",cn:"多可爱的小狗！"},
  {id:306,text:"I can not believe it!",type:"declarative",sub:"exclamatory",level:"elementary",cn:"我简直不敢相信！"},
  {id:307,text:"How delicious this cake is!",type:"declarative",sub:"exclamatory",level:"elementary",cn:"这蛋糕多美味！"},
  {id:308,text:"What a great idea!",type:"declarative",sub:"exclamatory",level:"elementary",cn:"多好的主意！"},
  {id:309,text:"That is incredible!",type:"declarative",sub:"exclamatory",level:"elementary",cn:"太不可思议了！"},

  // ===== EXCLAMATORY - INTERMEDIATE =====
  {id:310,text:"What an extraordinary performance that was!",type:"declarative",sub:"exclamatory",level:"intermediate",cn:"那是多么精彩的表演！"},
  {id:311,text:"How remarkable it is that technology has come so far!",type:"declarative",sub:"exclamatory",level:"intermediate",cn:"科技发展到如此程度真是太了不起了！"},
  {id:312,text:"What a tremendous achievement for the entire team!",type:"declarative",sub:"exclamatory",level:"intermediate",cn:"这对整个团队来说是多么巨大的成就！"},
  {id:313,text:"How inspiring it is to see young people making a difference!",type:"declarative",sub:"exclamatory",level:"intermediate",cn:"看到年轻人做出改变真是太鼓舞人心了！"},
  {id:314,text:"What a relief that everything worked out in the end!",type:"declarative",sub:"exclamatory",level:"intermediate",cn:"最后一切都好了，真是松了口气！"},
  {id:315,text:"How beautifully she played that piece!",type:"declarative",sub:"exclamatory",level:"intermediate",cn:"她把那首曲子演奏得多么优美！"},

  // ===== EXCLAMATORY - ADVANCED =====
  {id:316,text:"What an unprecedented paradigm shift this discovery represents!",type:"declarative",sub:"exclamatory",level:"advanced",cn:"这一发现代表了一个前所未有的范式转变！"},
  {id:317,text:"How profoundly the digital revolution has transformed contemporary society!",type:"declarative",sub:"exclamatory",level:"advanced",cn:"数字革命如此深刻地改变了当代社会！"},
  {id:318,text:"What a monumental breakthrough in renewable energy technology!",type:"declarative",sub:"exclamatory",level:"advanced",cn:"可再生能源技术的一个里程碑式突破！"},
];

// ==================== WORD DICTIONARY ====================
const DICTIONARY = {
  "name":{ipa:"/neɪm/",pos:"n.",cn:"名字",ex:["What is your name?","She has a beautiful name."]},
  "help":{ipa:"/hɛlp/",pos:"v./n.",cn:"帮助",ex:["Can you help me?","I need some help."]},
  "like":{ipa:"/laɪk/",pos:"v./prep.",cn:"喜欢；像",ex:["I like coffee.","She looks like her mother."]},
  "coffee":{ipa:"/ˈkɒfi/",pos:"n.",cn:"咖啡",ex:["Do you like coffee?","I drink coffee every morning."]},
  "time":{ipa:"/taɪm/",pos:"n.",cn:"时间",ex:["What time is it?","Time flies so fast."]},
  "book":{ipa:"/bʊk/",pos:"n.",cn:"书",ex:["Is this your book?","I read a book yesterday."]},
  "water":{ipa:"/ˈwɔːtər/",pos:"n.",cn:"水",ex:["Can I have some water?","The water is clean."]},
  "food":{ipa:"/fuːd/",pos:"n.",cn:"食物",ex:["What is your favorite food?","This food is delicious."]},
  "school":{ipa:"/skuːl/",pos:"n.",cn:"学校",ex:["We go to school every day.","The school is near my house."]},
  "friend":{ipa:"/frɛnd/",pos:"n.",cn:"朋友",ex:["She is my best friend.","I met a new friend today."]},
  "beautiful":{ipa:"/ˈbjuːtɪfəl/",pos:"adj.",cn:"美丽的",ex:["What a beautiful day!","The flowers are beautiful."]},
  "happy":{ipa:"/ˈhæpi/",pos:"adj.",cn:"快乐的",ex:["What makes you happy?","I feel very happy today."]},
  "language":{ipa:"/ˈlæŋɡwɪdʒ/",pos:"n.",cn:"语言",ex:["Learning a foreign language is important.","English is a global language."]},
  "technology":{ipa:"/tɛkˈnɒlədʒi/",pos:"n.",cn:"技术",ex:["Technology is changing rapidly.","We rely on technology every day."]},
  "exercise":{ipa:"/ˈɛksərsaɪz/",pos:"n./v.",cn:"锻炼；练习",ex:["Regular exercise is good for health.","How often do you exercise?"]},
  "career":{ipa:"/kəˈrɪr/",pos:"n.",cn:"职业；事业",ex:["She decided to change her career.","He has a successful career."]},
  "experience":{ipa:"/ɪkˈspɪriəns/",pos:"n.",cn:"经验；经历",ex:["She has ten years of experience.","It was an amazing experience."]},
  "environment":{ipa:"/ɪnˈvaɪrənmənt/",pos:"n.",cn:"环境",ex:["We must protect the environment.","The work environment is friendly."]},
  "economy":{ipa:"/ɪˈkɒnəmi/",pos:"n.",cn:"经济",ex:["The global economy is growing.","We need a strong economy."]},
  "intelligence":{ipa:"/ɪnˈtɛlɪdʒəns/",pos:"n.",cn:"智力；情报",ex:["Artificial intelligence is advancing.","He shows great intelligence."]},
  "sustainable":{ipa:"/səˈsteɪnəbl/",pos:"adj.",cn:"可持续的",ex:["Sustainable energy is the future.","We need sustainable development."]},
  "paradigm":{ipa:"/ˈpærəˌdaɪm/",pos:"n.",cn:"范式；典范",ex:["A paradigm shift has occurred.","The old paradigm no longer works."]},
  "philosophy":{ipa:"/fɪˈlɒsəfi/",pos:"n.",cn:"哲学",ex:["She studies philosophy at university.","His philosophy of life is simple."]},
  "research":{ipa:"/rɪˈsɜːrtʃ/",pos:"n./v.",cn:"研究",ex:["The research findings are promising.","She researches climate change."]},
  "education":{ipa:"/ˌɛdʒuˈkeɪʃən/",pos:"n.",cn:"教育",ex:["Education is very important.","She works in education."]},
  "opportunity":{ipa:"/ˌɒpərˈtjuːnɪti/",pos:"n.",cn:"机会",ex:["This is a great opportunity.","Opportunities come to those who work hard."]},
  "communication":{ipa:"/kəˌmjuːnɪˈkeɪʃən/",pos:"n.",cn:"交流；通讯",ex:["Good communication is essential.","Communication skills matter."]},
  "society":{ipa:"/səˈsaɪəti/",pos:"n.",cn:"社会",ex:["We live in a complex society.","Society is always changing."]},
  "decision":{ipa:"/dɪˈsɪʒən/",pos:"n.",cn:"决定",ex:["Making decisions is hard.","It was a difficult decision."]},
  "challenge":{ipa:"/ˈtʃælɪndʒ/",pos:"n./v.",cn:"挑战",ex:["Climate change is a big challenge.","She challenged herself."]},
  "discover":{ipa:"/dɪsˈkʌvər/",pos:"v.",cn:"发现",ex:["Scientists discover new species.","He discovered his passion."]},
  "important":{ipa:"/ɪmˈpɔːrtənt/",pos:"adj.",cn:"重要的",ex:["This is very important.","Education is important."]},
  "different":{ipa:"/ˈdɪfərənt/",pos:"adj.",cn:"不同的",ex:["We have different opinions.","Each person is different."]},
  "understand":{ipa:"/ˌʌndərˈstænd/",pos:"v.",cn:"理解",ex:["Do you understand me?","I understand the problem now."]},
  "remember":{ipa:"/rɪˈmɛmbər/",pos:"v.",cn:"记住",ex:["Remember to call me.","I remember that day clearly."]},
  "practice":{ipa:"/ˈpræktɪs/",pos:"n./v.",cn:"练习；实践",ex:["Practice makes perfect.","She practices piano daily."]},
  "success":{ipa:"/səkˈsɛs/",pos:"n.",cn:"成功",ex:["Hard work leads to success.","The project was a great success."]},
  "change":{ipa:"/tʃeɪndʒ/",pos:"v./n.",cn:"改变；变化",ex:["Change is inevitable.","We need to change our approach."]},
  "world":{ipa:"/wɜːrld/",pos:"n.",cn:"世界",ex:["The world is vast.","She wants to travel the world."]},
  "people":{ipa:"/ˈpiːpl/",pos:"n.",cn:"人们",ex:["Many people live here.","People are generally kind."]},
  "think":{ipa:"/θɪŋk/",pos:"v.",cn:"想；认为",ex:["What do you think?","I think it is a good idea."]},
  "learn":{ipa:"/lɜːrn/",pos:"v.",cn:"学习",ex:["I want to learn English.","We learn from our mistakes."]},
  "work":{ipa:"/wɜːrk/",pos:"v./n.",cn:"工作",ex:["I work in an office.","Hard work pays off."]},
  "play":{ipa:"/pleɪ/",pos:"v./n.",cn:"玩；演奏",ex:["Do you want to play?","She plays violin beautifully."]},
  "read":{ipa:"/riːd/",pos:"v.",cn:"阅读",ex:["I read books every day.","She reads very fast."]},
  "write":{ipa:"/raɪt/",pos:"v.",cn:"写",ex:["Write your name here.","She writes poems."]},
  "open":{ipa:"/ˈoʊpən/",pos:"v./adj.",cn:"打开；开放的",ex:["Please open the door.","The store is open."]},
  "close":{ipa:"/kloʊz/",pos:"v./adj.",cn:"关闭；近的",ex:["Close the window.","My house is close to school."]},
  "big":{ipa:"/bɪɡ/",pos:"adj.",cn:"大的",ex:["We live in a big city.","That is a big house."]},
  "small":{ipa:"/smɔːl/",pos:"adj.",cn:"小的",ex:["She has a small dog.","The room is very small."]},
  "good":{ipa:"/ɡʊd/",pos:"adj.",cn:"好的",ex:["Good morning!","This is a good book."]},
  "new":{ipa:"/njuː/",pos:"adj.",cn:"新的",ex:["I bought a new phone.","She started a new job."]},
  "old":{ipa:"/oʊld/",pos:"adj.",cn:"旧的；老的",ex:["How old are you?","That is an old building."]},
  "day":{ipa:"/deɪ/",pos:"n.",cn:"天；白天",ex:["What a beautiful day!","Today is a good day."]},
  "morning":{ipa:"/ˈmɔːrnɪŋ/",pos:"n.",cn:"早晨",ex:["Good morning!","I wake up early in the morning."]},
  "night":{ipa:"/naɪt/",pos:"n.",cn:"夜晚",ex:["Good night!","The stars shine at night."]},
  "today":{ipa:"/təˈdeɪ/",pos:"adv./n.",cn:"今天",ex:["How are you today?","Today is Monday."]},
  "year":{ipa:"/jɪr/",pos:"n.",cn:"年",ex:["Happy new year!","She is ten years old."]},
  "house":{ipa:"/haʊs/",pos:"n.",cn:"房子",ex:["I live in a big house.","The house is very old."]},
  "city":{ipa:"/ˈsɪti/",pos:"n.",cn:"城市",ex:["We live in a big city.","The city is very beautiful."]},
  "family":{ipa:"/ˈfæməli/",pos:"n.",cn:"家庭",ex:["I love my family.","Family is important."]},
  "mother":{ipa:"/ˈmʌðər/",pos:"n.",cn:"母亲",ex:["My mother is a teacher.","She loves her mother."]},
  "father":{ipa:"/ˈfɑːðər/",pos:"n.",cn:"父亲",ex:["My father works in a bank.","He is a good father."]},
  "student":{ipa:"/ˈstjuːdənt/",pos:"n.",cn:"学生",ex:["She is a good student.","Many students study here."]},
  "teacher":{ipa:"/ˈtiːtʃər/",pos:"n.",cn:"老师",ex:["Who is your teacher?","The teacher is very kind."]},
  "doctor":{ipa:"/ˈdɒktər/",pos:"n.",cn:"医生",ex:["I want to be a doctor.","She went to see the doctor."]},
  "music":{ipa:"/ˈmjuːzɪk/",pos:"n.",cn:"音乐",ex:["I love listening to music.","She studies music."]},
  "movie":{ipa:"/ˈmuːvi/",pos:"n.",cn:"电影",ex:["The movie was really funny.","Let us watch a movie."]},
  "color":{ipa:"/ˈkʌlər/",pos:"n.",cn:"颜色",ex:["What color do you like?","My favorite color is blue."]},
  "garden":{ipa:"/ˈɡɑːrdən/",pos:"n.",cn:"花园",ex:["They play in the garden.","The garden is full of flowers."]},
  "rain":{ipa:"/reɪn/",pos:"n./v.",cn:"雨；下雨",ex:["Is it raining outside?","The rain stopped."]},
  "sun":{ipa:"/sʌn/",pos:"n.",cn:"太阳",ex:["The sun is very hot.","The sun rises in the east."]},
  "planet":{ipa:"/ˈplænɪt/",pos:"n.",cn:"行星",ex:["Earth is our planet.","Mars is the red planet."]},
  "animal":{ipa:"/ˈænɪməl/",pos:"n.",cn:"动物",ex:["Dogs are loyal animals.","I love animals."]},
  "attention":{ipa:"/əˈtɛnʃən/",pos:"n.",cn:"注意力",ex:["Pay attention to the lecture.","She needs attention."]},
  "government":{ipa:"/ˈɡʌvərnmənt/",pos:"n.",cn:"政府",ex:["The government passed a new law.","Government policy affects everyone."]},
  "development":{ipa:"/dɪˈvɛləpmənt/",pos:"n.",cn:"发展",ex:["Economic development is important.","Software development requires skill."]},
  "information":{ipa:"/ˌɪnfərˈmeɪʃən/",pos:"n.",cn:"信息",ex:["I need more information.","Information spreads quickly online."]},
  "knowledge":{ipa:"/ˈnɒlɪdʒ/",pos:"n.",cn:"知识",ex:["Knowledge is power.","She has broad knowledge."]},
  "problem":{ipa:"/ˈprɒbləm/",pos:"n.",cn:"问题",ex:["We need to solve this problem.","No problem!"]},
  "question":{ipa:"/ˈkwɛstʃən/",pos:"n.",cn:"问题",ex:["Do you have any questions?","That is a good question."]},
  "answer":{ipa:"/ˈænsər/",pos:"n./v.",cn:"回答",ex:["What is the answer?","Please answer the question."]},
  "what":{ipa:"/wɒt/",pos:"pron./det.",cn:"什么",ex:["What is your name?","What time is it?"]},
  "how":{ipa:"/haʊ/",pos:"adv.",cn:"如何；怎样",ex:["How are you?","How much does it cost?"]},
  "where":{ipa:"/wɛr/",pos:"adv.",cn:"哪里",ex:["Where do you live?","Where is the station?"]},
  "when":{ipa:"/wɛn/",pos:"adv.",cn:"什么时候",ex:["When is your birthday?","When did you arrive?"]},
  "who":{ipa:"/huː/",pos:"pron.",cn:"谁",ex:["Who is your teacher?","Who are you?"]},
  "why":{ipa:"/waɪ/",pos:"adv.",cn:"为什么",ex:["Why are you late?","Why did you do that?"]},
  "is":{ipa:"/ɪz/",pos:"v.",cn:"是（be的第三人称单数）",ex:["What is your name?","She is my friend."]},
  "are":{ipa:"/ɑːr/",pos:"v.",cn:"是（be的复数形式）",ex:["How are you?","They are playing."]},
  "do":{ipa:"/duː/",pos:"v.",cn:"做",ex:["Do you like coffee?","What do you do?"]},
  "can":{ipa:"/kæn/",pos:"v.",cn:"能；可以",ex:["Can you help me?","I can swim."]},
  "have":{ipa:"/hæv/",pos:"v.",cn:"有",ex:["I have two brothers.","Have you been there?"]},
  "the":{ipa:"/ðə/",pos:"art.",cn:"这；那（定冠词）",ex:["The sun is hot.","Close the door."]},
  "a":{ipa:"/ə/",pos:"art.",cn:"一个（不定冠词）",ex:["She is a doctor.","I want a book."]},
  "this":{ipa:"/ðɪs/",pos:"pron./det.",cn:"这；这个",ex:["Is this your book?","This is my house."]},
  "that":{ipa:"/ðæt/",pos:"pron./det.",cn:"那；那个",ex:["That was great!","I know that."]},
  "it":{ipa:"/ɪt/",pos:"pron.",cn:"它",ex:["It is cold outside.","I like it."]},
  "you":{ipa:"/juː/",pos:"pron.",cn:"你；你们",ex:["How are you?","Thank you!"]},
  "i":{ipa:"/aɪ/",pos:"pron.",cn:"我",ex:["I like coffee.","I am a student."]},
  "she":{ipa:"/ʃiː/",pos:"pron.",cn:"她",ex:["She is my friend.","She plays piano."]},
  "he":{ipa:"/hiː/",pos:"pron.",cn:"他",ex:["He is a teacher.","He goes to school."]},
  "we":{ipa:"/wiː/",pos:"pron.",cn:"我们",ex:["We go to school.","We live in a city."]},
  "they":{ipa:"/ðeɪ/",pos:"pron.",cn:"他们",ex:["They are playing.","They live here."]},
  "my":{ipa:"/maɪ/",pos:"det.",cn:"我的",ex:["My name is Tom.","My dog is cute."]},
  "your":{ipa:"/jɔːr/",pos:"det.",cn:"你的",ex:["What is your name?","Your book is here."]},
  "very":{ipa:"/ˈvɛri/",pos:"adv.",cn:"非常",ex:["The sun is very hot.","She is very kind."]},
  "not":{ipa:"/nɒt/",pos:"adv.",cn:"不",ex:["I do not know.","It is not easy."]},
  "but":{ipa:"/bʌt/",pos:"conj.",cn:"但是",ex:["I like tea but not coffee.","It is small but nice."]},
  "and":{ipa:"/ænd/",pos:"conj.",cn:"和；而且",ex:["You and I are friends.","Read and write."]},
  "or":{ipa:"/ɔːr/",pos:"conj.",cn:"或者",ex:["Tea or coffee?","Do or die."]},
  "every":{ipa:"/ˈɛvri/",pos:"det.",cn:"每一个",ex:["We go to school every day.","Every person is unique."]},
  "some":{ipa:"/sʌm/",pos:"det.",cn:"一些",ex:["Can I have some water?","Some people like rain."]},
  "much":{ipa:"/mʌtʃ/",pos:"det./adv.",cn:"很多；非常",ex:["How much does it cost?","Thank you very much."]},
  "many":{ipa:"/ˈmɛni/",pos:"det.",cn:"许多",ex:["Many people came.","How many do you have?"]},
  "make":{ipa:"/meɪk/",pos:"v.",cn:"做；制作",ex:["Make sure you finish.","She makes cakes."]},
  "take":{ipa:"/teɪk/",pos:"v.",cn:"拿；带",ex:["Take a deep breath.","Take your time."]},
  "go":{ipa:"/ɡoʊ/",pos:"v.",cn:"去",ex:["We go to school.","Let us go!"]},
  "come":{ipa:"/kʌm/",pos:"v.",cn:"来",ex:["Come here quickly.","She comes from China."]},
  "see":{ipa:"/siː/",pos:"v.",cn:"看见",ex:["I can see the mountain.","See you tomorrow."]},
  "give":{ipa:"/ɡɪv/",pos:"v.",cn:"给",ex:["Give me the book.","She gives good advice."]},
  "eat":{ipa:"/iːt/",pos:"v.",cn:"吃",ex:["I like to eat apples.","Let us eat lunch."]},
  "drink":{ipa:"/drɪŋk/",pos:"v./n.",cn:"喝；饮料",ex:["I drink milk every morning.","Would you like a drink?"]},
  "live":{ipa:"/lɪv/",pos:"v.",cn:"生活；居住",ex:["Where do you live?","We live in a city."]},
  "speak":{ipa:"/spiːk/",pos:"v.",cn:"说；讲",ex:["Do you speak English?","She speaks three languages."]},
};
